# Form implementation generated from reading ui file 'Analysis2.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Naswail_Anlaysis(object):
    def setupUi(self, Ui_Naswail_Anlaysis):
        Ui_Naswail_Anlaysis.setObjectName("Ui_Naswail_Anlaysis")
        Ui_Naswail_Anlaysis.resize(1575, 3555)
        Ui_Naswail_Anlaysis.setMinimumSize(QtCore.QSize(1000, 1000))
        Ui_Naswail_Anlaysis.setStyleSheet("/* Main Application Background */\n"
"QWidget {\n"
"    background-color: #2D2A2E;\n"
"    color: #40E0D0; /* Turquoise text */\n"
"    font-family: \"Consolas\", \"Monospace\";\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Table View Text */\n"
"QTableView {\n"
"    color: #FFFFFF; /* White text for table content */\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"    background-color: #40E0D0; /* Turquoise */\n"
"    color: #2D2A2E;\n"
"    border: 1px solid #40E0D0;\n"
"    border-radius: 4px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #36C9B0;\n"
"    border: 1px solid #36C9B0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2DB39E;\n"
"    border: 1px solid #2DB39E;\n"
"}\n"
"\n"
"/* Text Inputs */\n"
"QLineEdit, QTextEdit {\n"
"    background-color: #3E3D40;\n"
"    color: #40E0D0; /* Turquoise text */\n"
"    border: 1px solid #5A595C;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #40E0D0;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #40E0D0;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Scrollbars */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background-color: rgba(90, 89, 92, 150);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* Graphics View */\n"
"QGraphicsView {\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"/* Menus */\n"
"QMenuBar {\n"
"    background-color: #2D2A2E;\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #5A595C;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #3E3D40;\n"
"    color: #40E0D0;\n"
"    border: 1px solid #5A595C;\n"
"}\n"
"\n"
"/* Tabs */\n"
"QTabBar::tab {\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Sliders */\n"
"QSlider::handle:horizontal {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Progress Bars */\n"
"QProgressBar {\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Checkboxes/Radio */\n"
"QCheckBox, QRadioButton {\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Group Boxes */\n"
"QGroupBox {\n"
"    color: #40E0D0;\n"
"}\n"
"")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Ui_Naswail_Anlaysis)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(240, 20, 1031, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.label_4 = QtWidgets.QLabel(parent=Ui_Naswail_Anlaysis)
        self.label_4.setGeometry(QtCore.QRect(90, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.graphicsView = QtWidgets.QGraphicsView(parent=Ui_Naswail_Anlaysis)
        self.graphicsView.setGeometry(QtCore.QRect(10, 20, 71, 61))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(parent=Ui_Naswail_Anlaysis)
        self.graphicsView_2.setGeometry(QtCore.QRect(10, 10, 81, 51))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=Ui_Naswail_Anlaysis)
        self.scrollArea.setGeometry(QtCore.QRect(20, 84, 1511, 3381))
        self.scrollArea.setMinimumSize(QtCore.QSize(1000, 0))
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1501, 13291))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(1291, 13291))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_9 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(800, 679, 521, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_9.setObjectName("label_9")
        self.widget_5 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget_5.setGeometry(QtCore.QRect(720, 729, 741, 481))
        self.widget_5.setObjectName("widget_5")
        self.widget_3 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget_3.setGeometry(QtCore.QRect(30, 2030, 781, 491))
        self.widget_3.setObjectName("widget_3")
        self.label_13 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_13.setGeometry(QtCore.QRect(910, 1859, 141, 20))
        self.label_13.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_13.setObjectName("label_13")
        self.widget = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(20, 737, 581, 471))
        self.widget.setObjectName("widget")
        self.label_8 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(310, 2550, 141, 20))
        self.label_8.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.comboBox_6 = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.comboBox_6.setGeometry(QtCore.QRect(940, 1262, 161, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.comboBox_2.setGeometry(QtCore.QRect(210, 1247, 161, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.comboBox_4.setGeometry(QtCore.QRect(300, 2590, 161, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.widget_4 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget_4.setGeometry(QtCore.QRect(720, 1399, 651, 421))
        self.widget_4.setObjectName("widget_4")
        self.comboBox_5 = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.comboBox_5.setGeometry(QtCore.QRect(900, 1899, 161, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(40, 689, 451, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(220, 1219, 141, 20))
        self.label_5.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_14 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_14.setGeometry(QtCore.QRect(950, 1222, 141, 20))
        self.label_14.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_14.setObjectName("label_14")
        self.label_10 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(810, 1339, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_7 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(160, 1969, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(60, 1329, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.widget_2 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget_2.setGeometry(QtCore.QRect(30, 1399, 591, 431))
        self.widget_2.setObjectName("widget_2")
        self.comboBox_3 = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        self.comboBox_3.setGeometry(QtCore.QRect(220, 1909, 161, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_6 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(230, 1869, 141, 20))
        self.label_6.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_6.setObjectName("label_6")
        self.widget_6 = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        self.widget_6.setGeometry(QtCore.QRect(40, 60, 1261, 551))
        self.widget_6.setObjectName("widget_6")
        self.label_11 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(60, 9, 1201, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(640, 2640, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_12.setObjectName("label_12")
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(60, 2710, 1371, 611))
        self.label.setObjectName("label")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Ui_Naswail_Anlaysis)
        QtCore.QMetaObject.connectSlotsByName(Ui_Naswail_Anlaysis)

    def retranslateUi(self, Ui_Naswail_Anlaysis):
        _translate = QtCore.QCoreApplication.translate
        Ui_Naswail_Anlaysis.setWindowTitle(_translate("Ui_Naswail_Anlaysis", "Form"))
        self.pushButton_4.setText(_translate("Ui_Naswail_Anlaysis", "Home"))
        self.pushButton_5.setText(_translate("Ui_Naswail_Anlaysis", "Incident Response"))
        self.pushButton_3.setText(_translate("Ui_Naswail_Anlaysis", "Tools"))
        self.pushButton_2.setText(_translate("Ui_Naswail_Anlaysis", "Analysis"))
        self.label_4.setText(_translate("Ui_Naswail_Anlaysis", "Naswail"))
        self.label_9.setText(_translate("Ui_Naswail_Anlaysis", "                        time series"))
        self.label_13.setText(_translate("Ui_Naswail_Anlaysis", "filter on:"))
        self.label_8.setText(_translate("Ui_Naswail_Anlaysis", "filter on:"))
        self.comboBox_6.setItemText(0, _translate("Ui_Naswail_Anlaysis", "Protocols"))
        self.comboBox_6.setItemText(1, _translate("Ui_Naswail_Anlaysis", "Sensors"))
        self.comboBox_6.setItemText(2, _translate("Ui_Naswail_Anlaysis", "Bandwidth"))
        self.comboBox_2.setItemText(0, _translate("Ui_Naswail_Anlaysis", "Protocols"))
        self.comboBox_2.setItemText(1, _translate("Ui_Naswail_Anlaysis", "Sensors"))
        self.comboBox_2.setItemText(2, _translate("Ui_Naswail_Anlaysis", "inside/outside"))
        self.comboBox_4.setItemText(0, _translate("Ui_Naswail_Anlaysis", "Protocols"))
        self.comboBox_4.setItemText(1, _translate("Ui_Naswail_Anlaysis", "inside/outside"))
        self.comboBox_4.setItemText(2, _translate("Ui_Naswail_Anlaysis", "Sensors"))
        self.comboBox_4.setItemText(3, _translate("Ui_Naswail_Anlaysis", "Bandwidth"))
        self.comboBox_5.setItemText(0, _translate("Ui_Naswail_Anlaysis", "Protocols"))
        self.comboBox_5.setItemText(1, _translate("Ui_Naswail_Anlaysis", "Sensors"))
        self.comboBox_5.setItemText(2, _translate("Ui_Naswail_Anlaysis", "Bandwidth"))
        self.label_2.setText(_translate("Ui_Naswail_Anlaysis", "                                 Pie Chart"))
        self.label_5.setText(_translate("Ui_Naswail_Anlaysis", "filter on:"))
        self.label_14.setText(_translate("Ui_Naswail_Anlaysis", "filter on:"))
        self.label_10.setText(_translate("Ui_Naswail_Anlaysis", "                 Heatmap"))
        self.label_7.setText(_translate("Ui_Naswail_Anlaysis", "                       Graph"))
        self.label_3.setText(_translate("Ui_Naswail_Anlaysis", "                        Hstogram"))
        self.comboBox_3.setItemText(0, _translate("Ui_Naswail_Anlaysis", "Protocols"))
        self.comboBox_3.setItemText(1, _translate("Ui_Naswail_Anlaysis", "inside/outside"))
        self.comboBox_3.setItemText(2, _translate("Ui_Naswail_Anlaysis", "Sensors"))
        self.label_6.setText(_translate("Ui_Naswail_Anlaysis", "filter on:"))
        self.label_11.setText(_translate("Ui_Naswail_Anlaysis", "                                                                            3D Network Topology Visulization"))
        self.label_12.setText(_translate("Ui_Naswail_Anlaysis", "Geo-Location Mapping"))
        self.label.setText(_translate("Ui_Naswail_Anlaysis", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_Naswail_Anlaysis = QtWidgets.QWidget()
    ui = Ui_Naswail_Anlaysis()
    ui.setupUi(Ui_Naswail_Anlaysis)
    Ui_Naswail_Anlaysis.show()
    sys.exit(app.exec())
