# Form implementation generated from reading ui file 'IncidentResponse.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt


class Ui_IncidentResponse(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1387, 873)
        Form.setStyleSheet("/* Main Application Background */\n"
"QWidget {\n"
"    background-color: #2D2A2E;\n"
"    color: #40E0D0;\n"
"    font-family: \"Consolas\", \"Monospace\";\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Table View Text */\n"
"QTableView {\n"
"    color: #FFFFFF; /* White text for table content */\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"    background-color: #40E0D0;\n"
"    color: #2D2A2E;\n"
"    border: 1px solid #40E0D0;\n"
"    border-radius: 4px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #36C9B0;\n"
"    border: 1px solid #36C9B0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2DB39E;\n"
"    border: 1px solid #2DB39E;\n"
"}\n"
"\n"
"/* Text Inputs */\n"
"QLineEdit, QTextEdit {\n"
"    background-color: #3E3D40;\n"
"    color: #40E0D0;\n"
"    border: 1px solid #5A595C;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #40E0D0;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #40E0D0;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Scrollbars */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background-color: rgba(90, 89, 92, 150);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* Scroll Area */\n"
"QScrollArea {\n"
"    border: 1px solid #5A595C;\n"
"    border-radius: 4px;\n"
"    background-color: #2D2A2E;\n"
"}\n"
"\n"
"QScrollArea > QWidget > QWidget {\n"
"    background-color: #2D2A2E;\n"
"}\n"
"\n"
"/* Graphics View */\n"
"QGraphicsView {\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"/* Menus */\n"
"QMenuBar {\n"
"    background-color: #2D2A2E;\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #5A595C;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #3E3D40;\n"
"    color: #40E0D0;\n"
"    border: 1px solid #5A595C;\n"
"}\n"
"\n"
"/* Tabs */\n"
"QTabBar::tab {\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Sliders */\n"
"QSlider::handle:horizontal {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Progress Bars */\n"
"QProgressBar {\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Checkboxes/Radio */\n"
"QCheckBox, QRadioButton {\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Group Boxes */\n"
"QGroupBox {\n"
"    color: #40E0D0;\n"
"    border: 1px solid #40E0D0;\n"
"    border-radius: 4px;\n"
"    margin-top: 10px;\n"
"    padding-top: 15px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 5px;\n"
"}\n"
"\n"
"/* ComboBox */\n"
"QComboBox {\n"
"    background-color: #3E3D40;\n"
"    color: #40E0D0;\n"
"    border: 1px solid #5A595C;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/down_arrow.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #3E3D40;\n"
"    color: #40E0D0;\n"
"    selection-background-color: #5A595C;\n"
"}\n"
"")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(180, 10, 1141, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        # Main suspicious packets table (left side, top) - adjusted height and spacing
        self.suspiciousGroupBox = QtWidgets.QGroupBox("Suspicious Packets", parent=Form)
        self.suspiciousGroupBox.setGeometry(QtCore.QRect(20, 80, 800, 380))  # Reduced height
        self.suspiciousGroupBox.setStyleSheet("""
            QGroupBox {
                color: #40E0D0;
                border: 1px solid #40E0D0;
                border-radius: 4px;
                margin-top: 10px;
                padding-top: 15px;
                font-weight: bold;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                subcontrol-position: top center;
                padding: 0 5px;
            }
        """)
        suspiciousLayout = QtWidgets.QVBoxLayout(self.suspiciousGroupBox)
        suspiciousLayout.setContentsMargins(10, 20, 10, 10)  # Added margins
        
        self.tableWidget = QtWidgets.QTableWidget()
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        suspiciousLayout.addWidget(self.tableWidget)
        
        # Attack intelligence table (right side, top) - adjusted height and spacing
        self.intelligenceGroupBox = QtWidgets.QGroupBox("Attack Intelligence", parent=Form)
        self.intelligenceGroupBox.setGeometry(QtCore.QRect(850, 80, 510, 380))  # Reduced height
        self.intelligenceGroupBox.setStyleSheet("""
            QGroupBox {
                color: #40E0D0;
                border: 1px solid #40E0D0;
                border-radius: 4px;
                margin-top: 10px;
                padding-top: 15px;
                font-weight: bold;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                subcontrol-position: top center;
                padding: 0 5px;
            }
        """)
        intelligenceLayout = QtWidgets.QVBoxLayout(self.intelligenceGroupBox)
        intelligenceLayout.setContentsMargins(10, 20, 10, 10)  # Added margins
        
        self.tableWidget_3 = QtWidgets.QTableWidget()
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        intelligenceLayout.addWidget(self.tableWidget_3)
        
        # Auto-Pilot Activity Log (left side, bottom) - adjusted position and height
        self.logGroupBox = QtWidgets.QGroupBox("Auto-Pilot Activity Log", parent=Form)
        self.logGroupBox.setGeometry(QtCore.QRect(20, 480, 800, 350))  # Moved up and increased height
        self.logGroupBox.setStyleSheet("""
            QGroupBox {
                color: #40E0D0;
                border: 1px solid #40E0D0;
                border-radius: 4px;
                margin-top: 10px;
                padding-top: 15px;
                font-weight: bold;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                subcontrol-position: top center;
                padding: 0 5px;
            }
        """)
        logLayout = QtWidgets.QVBoxLayout(self.logGroupBox)
        logLayout.setContentsMargins(10, 20, 10, 10)  # Added margins
        
        self.treeView = QtWidgets.QTreeView()
        self.treeView.setStyleSheet("QTreeView {\n"
"   border: 1px solid #76797C;\n"
"    gridline-color: #31363b;\n"
"    background-color: #232629;\n"
"}\n"
"")
        self.treeView.setObjectName("treeView")
        logLayout.addWidget(self.treeView)
        
        # Tab widget (right side, bottom) - adjusted position and height
        self.mitigationGroupBox = QtWidgets.QGroupBox("Mitigation Controls", parent=Form)
        self.mitigationGroupBox.setGeometry(QtCore.QRect(850, 480, 510, 350))  # Moved up and increased height
        self.mitigationGroupBox.setStyleSheet("""
            QGroupBox {
                color: #40E0D0;
                border: 1px solid #40E0D0;
                border-radius: 4px;
                margin-top: 10px;
                padding-top: 15px;
                font-weight: bold;
            }
            QGroupBox::title {
                subcontrol-origin: margin;
                subcontrol-position: top center;
                padding: 0 5px;
            }
        """)
        mitigationLayout = QtWidgets.QVBoxLayout(self.mitigationGroupBox)
        mitigationLayout.setContentsMargins(10, 20, 10, 10)  # Added margins
        
        self.tabWidget = QtWidgets.QTabWidget()
        self.tabWidget.setObjectName("tabWidget")
        mitigationLayout.addWidget(self.tabWidget)
        
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.listView = QtWidgets.QListView(parent=self.tab)
        self.listView.setGeometry(QtCore.QRect(10, 10, 200, 240))  # Adjusted size
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setGeometry(QtCore.QRect(220, 10, 220, 25))  # Adjusted position
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(220, 40, 220, 30))  # Adjusted position
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border: 1px solid #76797C;\n"
"    gridline-color: #31363b;\n"
"    background-color: #232629;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton.setGeometry(QtCore.QRect(220, 80, 105, 30))  # Adjusted position
        self.pushButton.setObjectName("pushButton")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_9.setGeometry(QtCore.QRect(335, 80, 105, 30))  # Adjusted position
        self.pushButton_9.setObjectName("pushButton_9")
        self.tabWidget.addTab(self.tab, "")
        
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 10, 200, 240))  # Adjusted size
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.label_3 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(220, 10, 220, 25))  # Adjusted position
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 40, 220, 30))  # Adjusted position
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border: 1px solid #76797C;\n"
"    gridline-color: #31363b;\n"
"    background-color: #232629;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(220, 80, 105, 30))  # Adjusted position
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(335, 80, 105, 30))  # Adjusted position
        self.pushButton_11.setObjectName("pushButton_11")
        self.tabWidget.addTab(self.tab_2, "")
        
        # Terminate Process tab
        self.terminateTab = QtWidgets.QWidget()
        self.terminateTab.setObjectName("terminateTab")

        # Create layout for terminate tab with adjusted margins
        self.terminateLayout = QtWidgets.QGridLayout(self.terminateTab)
        self.terminateLayout.setContentsMargins(10, 10, 10, 10)
        self.terminateLayout.setSpacing(10)

        # Terminated processes list with adjusted size
        self.terminatedLabel = QtWidgets.QLabel("Terminated Processes")
        self.terminatedLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.terminatedList = QtWidgets.QListView()
        self.terminatedList.setMinimumHeight(200)  # Set minimum height

        # Process termination controls with adjusted spacing
        self.processLabel = QtWidgets.QLabel("Name of Process to Terminate")
        self.processLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.processLineEdit = QtWidgets.QLineEdit()
        self.processLineEdit.setStyleSheet("QLineEdit{\n"
"border: 1px solid #76797C;\n"
"    gridline-color: #31363b;\n"
"    background-color: #232629;\n"
"}")
        self.terminateButton = QtWidgets.QPushButton("Terminate")
        self.terminateButton.setMinimumHeight(30)  # Set minimum height

        # Add widgets to grid layout with better spacing
        self.terminateLayout.addWidget(self.terminatedLabel, 0, 0)
        self.terminateLayout.addWidget(self.terminatedList, 1, 0)
        self.terminateLayout.addWidget(self.processLabel, 0, 1)
        self.terminateLayout.addWidget(self.processLineEdit, 1, 1)
        self.terminateLayout.addWidget(self.terminateButton, 2, 1)

        # Packet Rate Limiting tab
        self.rateLimitTab = QtWidgets.QWidget()
        self.rateLimitTab.setObjectName("rateLimitTab")

        # Create layout for rate limit tab with adjusted margins
        self.rateLimitLayout = QtWidgets.QGridLayout(self.rateLimitTab)
        self.rateLimitLayout.setContentsMargins(10, 10, 10, 10)
        self.rateLimitLayout.setSpacing(10)

        # Limited IPs list with adjusted size
        self.limitedIPsLabel = QtWidgets.QLabel("Limited IPs")
        self.limitedIPsLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.limitedIPsList = QtWidgets.QListView()
        self.limitedIPsList.setMinimumHeight(200)  # Set minimum height

        # Rate limiting controls with adjusted spacing
        self.ipLabel = QtWidgets.QLabel("IP Address to Limit")
        self.ipLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ipLineEdit = QtWidgets.QLineEdit()
        self.ipLineEdit.setStyleSheet("QLineEdit{\n"
"border: 1px solid #76797C;\n"
"    gridline-color: #31363b;\n"
"    background-color: #232629;\n"
"}")

        self.rateLabel = QtWidgets.QLabel("Rate Limit (Kbits/sec, min 8)")
        self.rateLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.rateLineEdit = QtWidgets.QLineEdit()
        self.rateLineEdit.setStyleSheet("QLineEdit{\n"
"border: 1px solid #76797C;\n"
"    gridline-color: #31363b;\n"
"    background-color: #232629;\n"
"}")

        self.applyLimitButton = QtWidgets.QPushButton("Apply Limit")
        self.resetbutton = QtWidgets.QPushButton("Reset Limits")
        self.applyLimitButton.setMinimumHeight(30)  # Set minimum height
        self.resetbutton.setMinimumHeight(30)  # Set minimum height

        # Add widgets to grid layout with better spacing
        self.rateLimitLayout.addWidget(self.limitedIPsLabel, 0, 0)
        self.rateLimitLayout.addWidget(self.limitedIPsList, 1, 0, 4, 1)  # span 4 rows
        self.rateLimitLayout.addWidget(self.ipLabel, 0, 1)
        self.rateLimitLayout.addWidget(self.ipLineEdit, 1, 1)
        self.rateLimitLayout.addWidget(self.rateLabel, 2, 1)
        self.rateLimitLayout.addWidget(self.rateLineEdit, 3, 1)
        self.rateLimitLayout.addWidget(self.applyLimitButton, 4, 1)
        self.rateLimitLayout.addWidget(self.resetbutton, 5, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_8.setText(_translate("Form", "Home"))
        self.pushButton_5.setText(_translate("Form", "Incident Response"))
        self.pushButton_6.setText(_translate("Form", "Tools"))
        self.pushButton_7.setText(_translate("Form", "Analysis"))
        self.label_2.setText(_translate("Form", "Naswail"))
        self.pushButton.setText(_translate("Form", "Add"))
        self.pushButton_9.setText(_translate("Form", "Remove"))
        self.label.setText(_translate("Form", "Enter IP Address"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Blacklist"))
        self.label_3.setText(_translate("Form", "Enter Port Number"))
        self.pushButton_10.setText(_translate("Form", "Add"))
        self.pushButton_11.setText(_translate("Form", "Remove"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Port Blocking"))
        self.tabWidget.addTab(self.terminateTab, "Terminate Process")
        self.tabWidget.addTab(self.rateLimitTab, "Packet Rate Limiting")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_IncidentResponse()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
