# Form implementation generated from reading ui file 'IncidentResponse.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_IncidentResponse(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1387, 873)
        Form.setStyleSheet("/* Main Application Background */\n"
"QWidget {\n"
"    background-color: #2D2A2E;\n"
"    color: #40E0D0; /* Turquoise text */\n"
"    font-family: \"Consolas\", \"Monospace\";\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Table View Text */\n"
"QTableView {\n"
"    color: #FFFFFF; /* White text for table content */\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"    background-color: #40E0D0; /* Turquoise */\n"
"    color: #2D2A2E;\n"
"    border: 1px solid #40E0D0;\n"
"    border-radius: 4px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #36C9B0;\n"
"    border: 1px solid #36C9B0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2DB39E;\n"
"    border: 1px solid #2DB39E;\n"
"}\n"
"\n"
"/* Text Inputs */\n"
"QLineEdit, QTextEdit {\n"
"    background-color: #3E3D40;\n"
"    color: #40E0D0; /* Turquoise text */\n"
"    border: 1px solid #5A595C;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #40E0D0;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #40E0D0;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Scrollbars */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background-color: rgba(90, 89, 92, 150);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* Graphics View */\n"
"QGraphicsView {\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"/* Menus */\n"
"QMenuBar {\n"
"    background-color: #2D2A2E;\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #5A595C;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #3E3D40;\n"
"    color: #40E0D0;\n"
"    border: 1px solid #5A595C;\n"
"}\n"
"\n"
"/* Tabs */\n"
"QTabBar::tab {\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Sliders */\n"
"QSlider::handle:horizontal {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Progress Bars */\n"
"QProgressBar {\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Checkboxes/Radio */\n"
"QCheckBox, QRadioButton {\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Group Boxes */\n"
"QGroupBox {\n"
"    color: #40E0D0;\n"
"}\n"
"")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(180, 10, 1141, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setGeometry(QtCore.QRect(50, 100, 731, 381))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tabWidget = QtWidgets.QTabWidget(parent=Form)
        self.tabWidget.setGeometry(QtCore.QRect(774, 500, 581, 291))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.listView = QtWidgets.QListView(parent=self.tab)
        self.listView.setGeometry(QtCore.QRect(5, 0, 331, 261))
        self.listView.setObjectName("listView")
        self.pushButton = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton.setGeometry(QtCore.QRect(360, 180, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_9.setGeometry(QtCore.QRect(460, 180, 93, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(360, 140, 191, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border: 1px solid #76797C;\n"
"    gridline-color: #31363b;\n"
"    background-color: #232629;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setGeometry(QtCore.QRect(360, 100, 161, 31))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(40, 40, 251, 211))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 140, 191, 31))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border: 1px solid #76797C;\n"
"    gridline-color: #31363b;\n"
"    background-color: #232629;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(330, 100, 161, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(330, 180, 93, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(430, 180, 93, 28))
        self.pushButton_11.setObjectName("pushButton_11")
        self.tabWidget.addTab(self.tab_2, "")
        self.treeView = QtWidgets.QTreeView(parent=Form)
        self.treeView.setGeometry(QtCore.QRect(30, 530, 641, 271))
        self.treeView.setStyleSheet("QTreeView {\n"
"   border: 1px solid #76797C;\n"
"    gridline-color: #31363b;\n"
"    background-color: #232629;\n"
"}\n"
"")
        self.treeView.setObjectName("treeView")
        self.tableWidget_3 = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget_3.setGeometry(QtCore.QRect(850, 100, 501, 381))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(230, 490, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(1020, 60, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(300, 60, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_8.setText(_translate("Form", "Home"))
        self.pushButton_5.setText(_translate("Form", "Incident Response"))
        self.pushButton_6.setText(_translate("Form", "Tools"))
        self.pushButton_7.setText(_translate("Form", "Analysis"))
        self.label_2.setText(_translate("Form", "Naswail"))
        self.pushButton.setText(_translate("Form", "Add"))
        self.pushButton_9.setText(_translate("Form", "Remove"))
        self.label.setText(_translate("Form", "Enter IP Address"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Blacklist"))
        self.label_3.setText(_translate("Form", "Enter Port Number"))
        self.pushButton_10.setText(_translate("Form", "Add"))
        self.pushButton_11.setText(_translate("Form", "Remove"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Port Blocking"))
        self.label_4.setText(_translate("Form", " Auto-Pilot Acitvity Log"))
        self.label_5.setText(_translate("Form", "Attack Intelligence"))
        self.label_6.setText(_translate("Form", "Suspecious Packets"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_IncidentResponse()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
