# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
       
        
        MainWindow.setStyleSheet("/* Main Application Background */\n"
"QWidget {\n"
"    background-color: #2D2A2E;\n"
"    color: #40E0D0; /* Turquoise text */\n"
"    font-family: \"Consolas\", \"Monospace\";\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Table View Text */\n"
"QTableView {\n"
"    color: #FFFFFF; /* White text for table content */\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"    background-color: #40E0D0; /* Turquoise */\n"
"    color: #2D2A2E;\n"
"    border: 1px solid #40E0D0;\n"
"    border-radius: 4px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #36C9B0;\n"
"    border: 1px solid #36C9B0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2DB39E;\n"
"    border: 1px solid #2DB39E;\n"
"}\n"
"\n"
"/* Text Inputs */\n"
"QLineEdit, QTextEdit {\n"
"    background-color: #3E3D40;\n"
"    color: #40E0D0; /* Turquoise text */\n"
"    border: 1px solid #5A595C;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #40E0D0;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #40E0D0;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Scrollbars */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background-color: rgba(90, 89, 92, 150);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* Graphics View */\n"
"QGraphicsView {\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"/* Menus */\n"
"QMenuBar {\n"
"    background-color: #2D2A2E;\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #5A595C;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #3E3D40;\n"
"    color: #40E0D0;\n"
"    border: 1px solid #5A595C;\n"
"}\n"
"\n"
"/* Tabs */\n"
"QTabBar::tab {\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Sliders */\n"
"QSlider::handle:horizontal {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Progress Bars */\n"
"QProgressBar {\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Checkboxes/Radio */\n"
"QCheckBox, QRadioButton {\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Group Boxes */\n"
"QGroupBox {\n"
"    color: #40E0D0;\n"
"}\n"
"")

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(12, 437, 781, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_7 = QtWidgets.QLabel(parent=self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 161, 21))
        self.label_7.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_7.setObjectName("label_7")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(parent=self.tab)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(0, 110, 194, 38))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.label_8 = QtWidgets.QLabel(parent=self.tab)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 161, 21))
        self.label_8.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.tab)
        self.dateTimeEdit.setGeometry(QtCore.QRect(0, 30, 194, 38))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(630, 30, 142, 38))
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"\n"
"\n"
"        color: white;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_9 = QtWidgets.QLabel(parent=self.tab)
        self.label_9.setGeometry(QtCore.QRect(650, 0, 55, 16))
        self.label_9.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_9.setObjectName("label_9")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(240, 40, 187, 220))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.checkBox = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkBox_6)
        self.checkBox_8 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_8.setObjectName("checkBox_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_9.setObjectName("checkBox_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_10.setObjectName("checkBox_10")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkBox_10)
        self.checkBox_7 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkBox_7)
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setGeometry(QtCore.QRect(250, 10, 171, 20))
        self.label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(460, 40, 142, 38))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_10 = QtWidgets.QLabel(parent=self.tab)
        self.label_10.setGeometry(QtCore.QRect(460, 20, 151, 20))
        self.label_10.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_15 = QtWidgets.QLabel(parent=self.tab)
        self.label_15.setGeometry(QtCore.QRect(460, 80, 151, 20))
        self.label_15.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_15.setObjectName("label_15")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(460, 100, 142, 38))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.comboBox = QtWidgets.QComboBox(parent=self.tab)
        self.comboBox.setGeometry(QtCore.QRect(460, 150, 150, 38))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(parent=self.tab)
        self.label_3.setGeometry(QtCore.QRect(460, 130, 151, 20))
        self.label_3.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton.setGeometry(QtCore.QRect(620, 140, 126, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_9.setGeometry(QtCore.QRect(470, 210, 126, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.listView = QtWidgets.QListView(parent=self.tab_2)
        self.listView.setGeometry(QtCore.QRect(0, 0, 791, 231))
        self.listView.setObjectName("listView")
        self.tabWidget.addTab(self.tab_2, "")
       
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.tab_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(562, 70, 211, 38))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.tab_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(542, 170, 211, 38))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_11 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(620, 40, 101, 20))
        self.label_11.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(620, 130, 101, 20))
        self.label_12.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_12.setObjectName("label_12")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.tab_3)
        self.buttonBox.setGeometry(QtCore.QRect(570, 170, 193, 28))
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(parent=self.tab_3)
        self.buttonBox_2.setGeometry(QtCore.QRect(560, 220, 193, 41))
        self.buttonBox_2.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Discard)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.label_13 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(564, 0, 191, 20))
        self.label_13.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_13.setObjectName("label_13")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(160, 230, 126, 38))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_14 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(150, 1, 181, 20))
        self.label_14.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_14.setObjectName("label_14")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.tab_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(5, 30, 461, 191))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.tab_5)
        self.pushButton_8.setGeometry(QtCore.QRect(600, 30, 126, 38))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_16 = QtWidgets.QLabel(parent=self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(240, 0, 161, 20))
        self.label_16.setObjectName("label_16")
        self.tableWidget_3 = QtWidgets.QTableWidget(parent=self.tab_5)
        self.tableWidget_3.setGeometry(QtCore.QRect(20, 0, 561, 341))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.listView_2 = QtWidgets.QListView(parent=self.tab_6)
        self.listView_2.setGeometry(QtCore.QRect(0, 0, 791, 231))
        self.tabWidget.addTab(self.tab_6, "Packet Decode")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.listView_3 = QtWidgets.QListView(parent=self.tab_7)
        self.listView_3.setGeometry(QtCore.QRect(0, 0, 791, 231))
        self.tabWidget.addTab(self.tab_7, "Packet statictics")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.listView_4 = QtWidgets.QListView(parent=self.tab_8)
        self.listView_4.setGeometry(QtCore.QRect(0, 0, 391, 231))
        self.listView_4.setObjectName("listView_4")
        self.label_17 = QtWidgets.QLabel(parent=self.tab_8)
        self.label_17.setGeometry(QtCore.QRect(500, 110, 161, 20))
        self.label_17.setObjectName("label_17")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.tab_8)
        self.lineEdit_6.setGeometry(QtCore.QRect(500, 139, 171, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.tab_8)
        self.pushButton_10.setGeometry(QtCore.QRect(500, 180, 84, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.tab_8)
        self.pushButton_11.setGeometry(QtCore.QRect(590, 180, 84, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.tabWidget.addTab(self.tab_8, "Blacklist")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.listView_5 = QtWidgets.QListView(parent=self.tab_9)
        self.listView_5.setGeometry(QtCore.QRect(0, 0, 391, 231))
        self.listView_5.setObjectName("listView_5")
        self.label_18 = QtWidgets.QLabel(parent=self.tab_9)
        self.label_18.setGeometry(QtCore.QRect(500, 100, 261, 120))
        self.label_18.setObjectName("label_18")
        self.tab_fabricate_packet = QtWidgets.QWidget()



        # Increase size and set color to white
        self.label_18.setStyleSheet("color: white; font-size: 16px;")  # Set text color to white and font size
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.tab_9)
        self.pushButton_12.setGeometry(QtCore.QRect(500, 180, 84, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.tabWidget.addTab(self.tab_9, "Logging")
        self.tab_fabricate_packet.setObjectName("tab_fabricate_packet")

        # IP Source Label
                # IP Source Label
        self.label_ip_source = QtWidgets.QLabel(parent=self.tab_fabricate_packet)
        self.label_ip_source.setGeometry(QtCore.QRect(10, 20, 100, 20))
        self.label_ip_source.setObjectName("label_ip_source")
        self.label_ip_source.setStyleSheet("color: white; font-size: 12px;")  # Set text color to white and font size

        # IP Source LineEdit
        self.lineEdit_ip_source = QtWidgets.QLineEdit(parent=self.tab_fabricate_packet)
        self.lineEdit_ip_source.setGeometry(QtCore.QRect(10, 40, 200, 30))
        self.lineEdit_ip_source.setObjectName("lineEdit_ip_source")
        self.lineEdit_ip_source.setStyleSheet("""
        background-color: gray;
        color: white;
        """)

        # IP Dst Label
        self.label_ip_dst = QtWidgets.QLabel(parent=self.tab_fabricate_packet)
        self.label_ip_dst.setGeometry(QtCore.QRect(10, 80, 100, 20))
        self.label_ip_dst.setObjectName("label_ip_dst")
        self.label_ip_dst.setStyleSheet("color: white; font-size: 12px;")

        # IP Dst LineEdit
        self.lineEdit_ip_dst = QtWidgets.QLineEdit(parent=self.tab_fabricate_packet)
        self.lineEdit_ip_dst.setGeometry(QtCore.QRect(10, 110, 200, 30))
        self.lineEdit_ip_dst.setObjectName("lineEdit_ip_dst")
        self.lineEdit_ip_dst.setStyleSheet("""
        background-color: gray;
        color: white;
        """)

        # Pick a Protocol Label
        self.label_protocol = QtWidgets.QLabel(parent=self.tab_fabricate_packet)
        self.label_protocol.setGeometry(QtCore.QRect(240, 10, 120, 20))
        self.label_protocol.setObjectName("label_protocol")
        self.label_protocol.setStyleSheet("color: white; font-size: 12px;")

        # Protocol ComboBox
        self.comboBox_protocol = QtWidgets.QComboBox(parent=self.tab_fabricate_packet)
        self.comboBox_protocol.setGeometry(QtCore.QRect(240, 40, 150, 30))
        self.comboBox_protocol.setObjectName("comboBox_protocol")
        self.comboBox_protocol.addItems(["TCP", "UDP", "ICMP", "FTP", "HTTP", "HTTPS", "DNS", "DHCP"])
        self.comboBox_protocol.setStyleSheet("""
        background-color: gray;
        color: black;
        """)

        # Apply Button
        self.pushButton_apply = QtWidgets.QPushButton(parent=self.tab_fabricate_packet)
        self.pushButton_apply.setGeometry(QtCore.QRect(10, 160, 100, 30))  # Position below the other widgets
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.pushButton_apply.setText("Apply")
        

        # Add the tab to the TabWidget
        self.tabWidget.addTab(self.tab_fabricate_packet, "Fabricate packet")


        #
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(266, 10, 1031, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout.addWidget(self.pushButton_13)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 0, 71, 61))
        self.graphicsView.setObjectName("graphicsView")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(81, 3, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(864, 433, 311, 20))
        self.label_4.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1270, 70, 91, 20))
        self.label_5.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1290, 110, 55, 16))
        self.label_6.setObjectName("label_6")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1270, 180, 126, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1270, 250, 126, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 60, 1231, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget_4 = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_4.setGeometry(QtCore.QRect(805, 460, 381, 271))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.graphicsView_2 = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(1210, 400, 300, 401))
        self.graphicsView_2.setObjectName("graphicsView_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1360, 26))
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(parent=self.menubar)
        self.menuHome.setObjectName("menuHome")
        self.menuTools = QtWidgets.QMenu(parent=self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuReports = QtWidgets.QMenu(parent=self.menubar)
        self.menuReports.setObjectName("menuReports")
        self.menuSettings = QtWidgets.QMenu(parent=self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.actionImport_Packets = QtGui.QAction(parent=MainWindow)
        self.actionImport_Packets.setObjectName("actionImport_Packets")
        self.actionExport_Packets = QtGui.QAction(parent=MainWindow)
        self.actionExport_Packets.setObjectName("actionExport_Packets")
        self.actionLive_Capture = QtGui.QAction(parent=MainWindow)
        self.actionLive_Capture.setObjectName("actionLive_Capture")
        self.menuHome.addAction(self.actionImport_Packets)
        self.menuHome.addAction(self.actionExport_Packets)
        self.menuHome.addAction(self.actionLive_Capture)
        self.menuTools.addSeparator()
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Start Time"))
        self.label_8.setText(_translate("MainWindow", "End Time"))
        self.label_9.setText(_translate("MainWindow", "Port"))
        self.checkBox.setText(_translate("MainWindow", "UDP"))
        self.checkBox_2.setText(_translate("MainWindow", "TCP"))
        self.checkBox_3.setText(_translate("MainWindow", "ICMP"))
        self.checkBox_4.setText(_translate("MainWindow", "DNS"))
        self.checkBox_5.setText(_translate("MainWindow", "HTTP"))
        self.checkBox_6.setText(_translate("MainWindow", "HTTPS"))
        self.checkBox_8.setText(_translate("MainWindow", "FTP"))
        self.checkBox_9.setText(_translate("MainWindow", "DHCP"))
        self.checkBox_10.setText(_translate("MainWindow", "Other"))
        self.checkBox_7.setText(_translate("MainWindow", "TELNET"))
        self.label.setText(_translate("MainWindow", "  Filter by Protocol"))
        self.label_10.setText(_translate("MainWindow", "Filter by source IP"))
        self.label_15.setText(_translate("MainWindow", "Filter by Destination IP"))
        self.comboBox.setItemText(0, _translate("MainWindow", "All"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Inside Traffic"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Outside Traffic"))
        self.label_3.setText(_translate("MainWindow", "Type Of Traffic"))
        self.pushButton.setText(_translate("MainWindow", "Reset"))
        self.pushButton_9.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Packet Filter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Packet Details"))
        self.label_11.setText(_translate("MainWindow", "Device name"))
        self.label_12.setText(_translate("MainWindow", "MAC Address"))
        self.label_13.setText(_translate("MainWindow", "              Add/Remove Sensor"))
        self.pushButton_7.setText(_translate("MainWindow", "Focus on"))
        self.label_14.setText(_translate("MainWindow", "                All Devices"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", " Sensors "))
        self.pushButton_8.setText(_translate("MainWindow", "Focus on"))
        self.pushButton_10.setText(_translate("MainWindow", "Add"))
        self.pushButton_11.setText(_translate("MainWindow", "Remove"))
        self.pushButton_12.setText(_translate("MainWindow", "Save"))
        self.label_16.setText(_translate("MainWindow", "Running Applications"))
        self.label_17.setText(_translate("MainWindow", "Enter IP Address"))
        self.label_18.setText(_translate("MainWindow", "Save Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Application Filter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Packet Decode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Packet Statistics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Blacklist"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Logging"))
        self.pushButton_4.setText(_translate("MainWindow", "Home"))
        self.pushButton_13.setText(_translate("MainWindow", "Incident Response"))
        self.pushButton_3.setText(_translate("MainWindow", "Tools"))
        self.pushButton_2.setText(_translate("MainWindow", "Analysis"))
        self.label_2.setText(_translate("MainWindow", "Naswail"))
        self.label_4.setText(_translate("MainWindow", "                      Suspicious Packets"))
        self.label_5.setText(_translate("MainWindow", "Time Elapsed:"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_ip_dst.setText(_translate("MainWindow", "Enter destination IP"))
        self.label_ip_source.setText(_translate("MainWindow", "Enter source IP"))
        self.label_protocol.setText(_translate("MainWindow", "Enter protocol"))
        self.pushButton_5.setText(_translate("MainWindow", "Start Capture"))
        self.pushButton_6.setText(_translate("MainWindow", "Stop Capture"))
        self.menuHome.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuReports.setTitle(_translate("MainWindow", "Reports"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionImport_Packets.setText(_translate("MainWindow", "Import Packets"))
        self.actionExport_Packets.setText(_translate("MainWindow", "Export Packets"))
        self.actionLive_Capture.setText(_translate("MainWindow", "Live Capture"))
