# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
       
        MainWindow.setStyleSheet("QWidget:window {                    /* Borders around the code editor and debug window */\n"
"        border: 1px solid #263238;\n"
"        background-color: #263238;\n"
"}\n"
"\n"
"QToolTip {\n"
"        background-color: #80CBC4;\n"
"        color: black;\n"
"    padding: 5px;\n"
"    border-radius: 0;\n"
"    opacity: 200;\n"
"}\n"
"\n"
"/* ==================== Dialog ==================== */\n"
"QLabel {\n"
    
"        color: white;                /* Not sure about this one */\n"
"}\n"
"\n"
"QDialog, QListView {\n"
"        background-color: #263238;\n"
"        color: #546E7A;\n"
"        outline: 0;\n"
"        border: 2px solid transparent;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"        color: #AFBDC4;\n"
"        background: transparent;\n"
"}\n"
"\n"
"\n"
"QListView::item:selected {\n"
"        color: #ffffff;\n"
"        background: transparent;\n"
"}\n"
"\n"
"/* === QTabBar === */\n"
"QTabBar {\n"
"        background: #263238;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"        background: transparent;    /* Only at the very bottom of the tabs */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"        background: transparent;\n"
"        border: 0px solid transparent;\n"
"        border-bottom: 2px solid transparent;\n"
"        color: #546E7A;\n"
"        padding-left: 10px;\n"
"        padding-right: 10px;\n"
"        padding-top: 3px;\n"
"        padding-bottom: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"        background-color: transparent;\n"
"        border: 0px solid transparent;\n"
"        border-bottom: 2px solid #80CBC4;\n"
"        color: #AFBDC4;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"        background-color: transparent;\n"
"        border: 0px solid transparent;\n"
"        border-top: none;\n"
"        border-bottom: 2px solid #80CBC4;\n"
"        color: #FFFFFF;\n"
"}\n"
"\n"
"QStackedWidget {\n"
"        background: #263238;    /* This covers a bunch of things, I was thinking about making it transparent, */\n"
"                                                        /* but I would have to find all the other elements... but QTabWidget::pane may be it */\n"
"}\n"
"\n"
"\n"
"/* === QGroupBox === */\n"
"QGroupBox {\n"
"    border: 1px solid transparent;\n"
"    margin-top: 1em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"        color: #80CBC4;\n"
"    subcontrol-origin: margin;\n"
"    left: 6px;\n"
"    padding: 0 3px 0 3px;\n"
"}\n"
"\n"
"QComboBox {\n"
"        color: #546E7A;\n"
"        background-color: transparent;\n"
"        selection-background-color: transparent;\n"
"        outline: 0;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    selection-background-color: transparent;\n"
"        outline: 0;\n"
"}\n"
"\n"
"QToolTip {\n"
"    border: 1px solid #76797C;\n"
"    background-color: #5A7566;\n"
"    color: white;\n"
"    padding: 0px;                /*remove padding, for fix combobox tooltip.*/\n"
"    opacity: 200;\n"
"}\n"
"\n"
"QWidget {\n"
"    color: #eff0f1;\n"
"    background-color: #31363b;\n"
"    selection-background-color: #3daee9;\n"
"    selection-color: #eff0f1;\n"
"    background-clip: border;\n"
"    border-image: none;\n"
"    border: 0px transparent black;\n"
"    outline: 0;\n"
"}\n"
"\n"
"QWidget:item:hover {\n"
"    background-color: #18465d;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QWidget:item:selected {\n"
"    background-color: #18465d;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    spacing: 5px;\n"
"    outline: none;\n"
"    color: #eff0f1;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QRadioButton:disabled {\n"
"    color: #76797C;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 21px;\n"
"    height: 21px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked {\n"
"    image: url(:/qss_icons/rc/radio_unchecked.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:hover,\n"
"QRadioButton::indicator:unchecked:focus,\n"
"QRadioButton::indicator:unchecked:pressed {\n"
"    border: none;\n"
"    outline: none;\n"
"    image: url(:/qss_icons/rc/radio_unchecked_focus.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border: none;\n"
"    outline: none;\n"
"    image: url(:/qss_icons/rc/radio_checked.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QRadioButton::indicator:checked:focus,\n"
"QRadioButton::indicator:checked:pressed {\n"
"    border: none;\n"
"    outline: none;\n"
"    image: url(:/qss_icons/rc/radio_checked_focus.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:disabled {\n"
"    outline: none;\n"
"    image: url(:/qss_icons/rc/radio_checked_disabled.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:disabled {\n"
"    image: url(:/qss_icons/rc/radio_unchecked_disabled.png);\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #31363b;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background: transparent;\n"
"    border: 1px solid #76797C;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"    border: 1px solid #76797C;\n"
"    background-color: #3daee9;\n"
"    color: #eff0f1;\n"
"    margin-bottom: -1px;\n"
"    padding-bottom: 1px;\n"
"}\n"
"\n"
"QMenu {\n"
"    border: 1px solid #76797C;\n"
"    color: #eff0f1;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QMenu::icon {\n"
"    margin: 5px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    padding: 5px 30px 5px 30px;\n"
"    border: 1px solid transparent;\n"
"    /* reserve space for selection border */\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 2px;\n"
"    background: lightblue;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"\n"
"\n"
"/* non-exclusive indicator = check box style indicator\n"
"   (see QActionGroup::setExclusive) */\n"
"\n"
"QMenu::indicator:non-exclusive:unchecked {\n"
"    image: url(:/qss_icons/rc/checkbox_unchecked.png);\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:unchecked:selected {\n"
"    image: url(:/qss_icons/rc/checkbox_unchecked_disabled.png);\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked {\n"
"    image: url(:/qss_icons/rc/checkbox_checked.png);\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked:selected {\n"
"    image: url(:/qss_icons/rc/checkbox_checked_disabled.png);\n"
"}\n"
"\n"
"\n"
"/* exclusive indicator = radio button style indicator (see QActionGroup::setExclusive) */\n"
"\n"
"QMenu::indicator:exclusive:unchecked {\n"
"    image: url(:/qss_icons/rc/radio_unchecked.png);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:unchecked:selected {\n"
"    image: url(:/qss_icons/rc/radio_unchecked_disabled.png);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked {\n"
"    image: url(:/qss_icons/rc/radio_checked.png);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked:selected {\n"
"    image: url(:/qss_icons/rc/radio_checked_disabled.png);\n"
"}\n"
"\n"
"QMenu::right-arrow {\n"
"    margin: 5px;\n"
"    image: url(:/qss_icons/rc/right_arrow.png)\n"
"}\n"
"\n"
"QWidget:disabled {\n"
"    color: #454545;\n"
"    background-color: #31363b;\n"
"}\n"
"\n"
"QAbstractItemView {\n"
"    alternate-background-color: #31363b;\n"
"    color: #eff0f1;\n"
"    border: 1px solid #3A3939;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QWidget:focus,\n"
"QMenuBar:focus {\n"
"    border: 1px solid #3daee9;\n"
"}\n"
"\n"
"QTabWidget:focus,\n"
"QCheckBox:focus,\n"
"QRadioButton:focus,\n"
"QSlider:focus {\n"
"    border: none;\n"
"}\n"
"\n"
"QLineEdit {\n"


"    color: white;\n"
"}\n"
"\n"
"QAbstractItemView QLineEdit {\n"
"    padding: 0;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid #76797C;\n"
"    border-radius: 2px;\n"
"    margin-top: 20px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QAbstractScrollArea {\n"
"    border-radius: 2px;\n"
"    border: 1px solid #76797C;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    height: 15px;\n"
"    margin: 3px 15px 3px 15px;\n"
"    border: 1px transparent #2A2929;\n"
"    border-radius: 4px;\n"
"    background-color: #2A2929;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #605F5F;\n"
"    min-width: 5px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    margin: 0px 3px 0px 3px;\n"
"    border-image: url(:/qss_icons/rc/right_arrow_disabled.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    margin: 0px 3px 0px 3px;\n"
"    border-image: url(:/qss_icons/rc/left_arrow_disabled.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover,\n"
"QScrollBar::add-line:horizontal:on {\n"
"    border-image: url(:/qss_icons/rc/right_arrow.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:hover,\n"
"QScrollBar::sub-line:horizontal:on {\n"
"    border-image: url(:/qss_icons/rc/left_arrow.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal,\n"
"QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background-color: #2A2929;\n"
"    width: 15px;\n"
"    margin: 15px 3px 15px 3px;\n"
"    border: 1px transparent #2A2929;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #605F5F;\n"
"    min-height: 5px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    margin: 3px 0px 3px 0px;\n"
"    border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    margin: 3px 0px 3px 0px;\n"
"    border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover,\n"
"QScrollBar::sub-line:vertical:on {\n"
"    border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover,\n"
"QScrollBar::add-line:vertical:on {\n"
"    border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QTextEdit {\n"
 
"   color: white"
"}\n"
"\n"
"QPlainTextEdit {\n"

"    ;\n"
"    color: white;\n"
"    border-radius: 2px;\n"

"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #76797C;\n"
"    color: #eff0f1;\n"
"    padding: 5px;\n"
"    border: 1px solid #76797C;\n"
"}\n"
"\n"
"QSizeGrip {\n"
"    image: url(:/qss_icons/rc/sizegrip.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QMainWindow::separator {\n"
"    background-color: #31363b;\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    spacing: 2px;\n"
"    border: 1px dashed #76797C;\n"
"}\n"
"\n"
"QMainWindow::separator:hover {\n"
"    background-color: #787876;\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #76797C;\n"
"    spacing: 2px;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background-color: #76797C;\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QFrame {\n"
"    border-radius: 2px;\n"
"    border: 1px solid #76797C;\n"
"}\n"
"\n"
"QFrame[frameShape=\"0\"] {\n"
"    border-radius: 2px;\n"
"    border: 1px transparent #76797C;\n"
"}\n"
"\n"
"QStackedWidget {\n"
"    border: 1px transparent black;\n"
"}\n"
"\n"
"QToolBar {\n"
"    border: 1px transparent #393838;\n"
"    background: 1px solid #31363b;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QToolBar::handle:horizontal {\n"
"    image: url(:/qss_icons/rc/Hmovetoolbar.png);\n"
"}\n"
"\n"
"QToolBar::handle:vertical {\n"
"    image: url(:/qss_icons/rc/Vmovetoolbar.png);\n"
"}\n"
"\n"
"QToolBar::separator:horizontal {\n"
"    image: url(:/qss_icons/rc/Hsepartoolbar.png);\n"
"}\n"
"\n"
"QToolBar::separator:vertical {\n"
"    image: url(:/qss_icons/rc/Vsepartoolbar.png);\n"
"}\n"
"\n"
"QToolButton#qt_toolbar_ext_button {\n"
"    background: #58595a\n"
"}\n"
"\n"
"\n"
"\n"
"QComboBox {\n"
"    selection-background-color: #3daee9;\n"
"    border-style: solid;\n"
"    border: 1px solid #76797C;\n"
"    border-radius: 2px;\n"
"    padding: 5px;\n"
"    min-width: 75px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 2px solid #8f8f91 transparent;\n"
"    border-radius: 6px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #0D71AC, stop: 1 transparent);\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 transparent);\n"
"}\n"
"\n"
"QPushButton:flat {\n"
"    border: none; /* no border for a flat push button */\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    border-color: navy; /* make the default button prominent */\n"
"}\n"
"\n"
"QPushButton:open { /* when the button has its menu open */\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"}\n"
"\n"
"QPushButton::menu-indicator {\n"
"    image: url(menu_indicator.png);\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"}\n"
"\n"
"QPushButton::menu-indicator:pressed, QPushButton::menu-indicator:open {\n"
"    position: relative;\n"
"    top: 2px; left: 2px; /* shift the arrow by 2 px */\n"
"}\n"
"\n"
"QComboBox:hover,\n"
"QAbstractSpinBox:hover,\n"
"QLineEdit:hover,\n"
"QTextEdit:hover,\n"
"QPlainTextEdit:hover,\n"
"QAbstractView:hover,\n"
"QTreeView:hover {\n"
"border: 1px solid #3daee9;\n"
"color: #eff0f1;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #4a4a4a;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #232629;\n"
"    border-radius: 2px;\n"
"    border: 1px solid #76797C;\n"
"    selection-background-color: #18465d;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 0px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on,\n"
"QComboBox::down-arrow:hover,\n"
"QComboBox::down-arrow:focus {\n"
"    image: url(:/qss_icons/rc/down_arrow.png);\n"
"}\n"
"\n"
"QAbstractSpinBox {\n"
"    padding: 5px;\n"
"    border: 1px solid #76797C;\n"
"    background-color: #232629;\n"
"    color: #eff0f1;\n"
"    border-radius: 2px;\n"
"    min-width: 75px;\n"
"}\n"
"\n"
"QAbstractSpinBox:up-button {\n"
"    background-color: transparent;\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: center right;\n"
"}\n"
"\n"
"QAbstractSpinBox:down-button {\n"
"    background-color: transparent;\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: center left;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow,\n"
"QAbstractSpinBox::up-arrow:disabled,\n"
"QAbstractSpinBox::up-arrow:off {\n"
"    image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow:hover {\n"
"    image: url(:/qss_icons/rc/up_arrow.png);\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow,\n"
"QAbstractSpinBox::down-arrow:disabled,\n"
"QAbstractSpinBox::down-arrow:off {\n"
"    image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow:hover {\n"
"    image: url(:/qss_icons/rc/down_arrow.png);\n"
"}\n"
"\n"
"QLabel {\n"
"    border: 0px solid black;\n"
"}\n"
"\n"
"QTabWidget {\n"
"    border: 0px transparent black;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #76797C;\n"
"    padding: 5px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    /* left: 5px; move to the right by 5px */\n"
"}\n"
"\n"
"QTabBar {\n"
"    qproperty-drawBase: 0;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QTabBar:focus {\n"
"    border: 0px transparent black;\n"
"}\n"
"\n"
"QTabBar::close-button {\n"
"    image: url(:/qss_icons/rc/close.png);\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTabBar::close-button:hover {\n"
"    image: url(:/qss_icons/rc/close-hover.png);\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTabBar::close-button:pressed {\n"
"    image: url(:/qss_icons/rc/close-pressed.png);\n"
"    background: transparent;\n"
"}\n"
"\n"
"\n"
"/* TOP TABS */\n"
"\n"
"QTabBar::tab:top {\n"
"    color: #eff0f1;\n"
"    border: 1px solid #76797C;\n"
"    border-bottom: 1px transparent black;\n"
"    background-color: #31363b;\n"
"    padding: 5px;\n"
"    min-width: 50px;\n"
"    border-top-left-radius: 2px;\n"
"    border-top-right-radius: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    color: #eff0f1;\n"
"    background-color: #54575B;\n"
"    border: 1px solid #76797C;\n"
"    border-bottom: 2px solid #3daee9;\n"
"    border-top-left-radius: 2px;\n"
"    border-top-right-radius: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected:hover {\n"
"    background-color: #3daee9;\n"
"}\n"
"\n"
"\n"
"/* BOTTOM TABS */\n"
"\n"
"QTabBar::tab:bottom {\n"
"    color: #eff0f1;\n"
"    border: 1px solid #76797C;\n"
"    border-top: 1px transparent black;\n"
"    background-color: #31363b;\n"
"    padding: 5px;\n"
"    border-bottom-left-radius: 2px;\n"
"    border-bottom-right-radius: 2px;\n"
"    min-width: 50px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected {\n"
"    color: #eff0f1;\n"
"    background-color: #54575B;\n"
"    border: 1px solid #76797C;\n"
"    border-top: 2px solid #3daee9;\n"
"    border-bottom-left-radius: 2px;\n"
"    border-bottom-right-radius: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected:hover {\n"
"    background-color: #3daee9;\n"
"}\n"
"\n"
"\n"
"/* LEFT TABS */\n"
"\n"
"QTabBar::tab:left {\n"
"    color: #eff0f1;\n"
"    border: 1px solid #76797C;\n"
"    border-left: 1px transparent black;\n"
"    background-color: #31363b;\n"
"    padding: 5px;\n"
"    border-top-right-radius: 2px;\n"
"    border-bottom-right-radius: 2px;\n"
"    min-height: 50px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected {\n"
"    color: #eff0f1;\n"
"    background-color: #54575B;\n"
"    border: 1px solid #76797C;\n"
"    border-left: 2px solid #3daee9;\n"
"    border-top-right-radius: 2px;\n"
"    border-bottom-right-radius: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected:hover {\n"
"    background-color: #3daee9;\n"
"}\n"
"\n"
"\n"
"/* RIGHT TABS */\n"
"\n"
"QTabBar::tab:right {\n"
"    color: #eff0f1;\n"
"    border: 1px solid #76797C;\n"
"    border-right: 1px transparent black;\n"
"    background-color: #31363b;\n"
"    padding: 5px;\n"
"    border-top-left-radius: 2px;\n"
"    border-bottom-left-radius: 2px;\n"
"    min-height: 50px;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected {\n"
"    color: #eff0f1;\n"
"    background-color: #54575B;\n"
"    border: 1px solid #76797C;\n"
"    border-right: 2px solid #3daee9;\n"
"    border-top-left-radius: 2px;\n"
"    border-bottom-left-radius: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected:hover {\n"
"    background-color: #3daee9;\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:enabled {\n"
"    image: url(:/qss_icons/rc/right_arrow.png);\n"
"}\n"
"\n"
"QTabBar QToolButton::left-arrow:enabled {\n"
"    image: url(:/qss_icons/rc/left_arrow.png);\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:disabled {\n"
"    image: url(:/qss_icons/rc/right_arrow_disabled.png);\n"
"}\n"
"\n"
"QTabBar QToolButton::left-arrow:disabled {\n"
"    image: url(:/qss_icons/rc/left_arrow_disabled.png);\n"
"}\n"
"\n"
"QDockWidget {\n"
"    background: #31363b;\n"
"    border: 1px solid #403F3F;\n"
"    titlebar-close-icon: url(:/qss_icons/rc/close.png);\n"
"    titlebar-normal-icon: url(:/qss_icons/rc/undock.png);\n"
"}\n"
"\n"
"QDockWidget::close-button,\n"
"QDockWidget::float-button {\n"
"    border: 1px solid transparent;\n"
"    border-radius: 2px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QDockWidget::close-button:hover,\n"
"QDockWidget::float-button:hover {\n"
"    background: rgba(255, 255, 255, 10);\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed,\n"
"QDockWidget::float-button:pressed {\n"
"    padding: 1px -1px -1px 1px;\n"
"    background: rgba(255, 255, 255, 10);\n"
"}\n"
"\n"
"QTreeView,\n"
"QListView {\n"
"    border: 1px solid #76797C;\n"
"    background-color: #232629;\n"
"}\n"
"\n"
"QTreeView:branch:selected,\n"
"QTreeView:branch:hover {\n"
"    background: url(:/qss_icons/rc/transparent.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:!adjoins-item {\n"
"    border-image: url(:/qss_icons/rc/transparent.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item {\n"
"    border-image: url(:/qss_icons/rc/transparent.png);\n"
"}\n"
"\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item {\n"
"    border-image: url(:/qss_icons/rc/transparent.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings {\n"
"    image: url(:/qss_icons/rc/branch_closed.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings {\n"
"    image: url(:/qss_icons/rc/branch_open.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed:hover,\n"
"QTreeView::branch:closed:has-children:has-siblings:hover {\n"
"    image: url(:/qss_icons/rc/branch_closed-on.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings:hover,\n"
"QTreeView::branch:open:has-children:has-siblings:hover {\n"
"    image: url(:/qss_icons/rc/branch_open-on.png);\n"
"}\n"
"\n"
"QListView::item:!selected:hover,\n"
"QTreeView::item:!selected:hover {\n"
"    background: #18465d;\n"
"    outline: 0;\n"
"    color: #eff0f1\n"
"}\n"
"\n"
"QListView::item:selected:hover,\n"
"QTreeView::item:selected:hover {\n"
"    background: #287399;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QTreeView::indicator:checked,\n"
"QListView::indicator:checked {\n"
"    image: url(:/qss_icons/rc/checkbox_checked.png);\n"
"}\n"
"\n"
"QTreeView::indicator:unchecked,\n"
"QListView::indicator:unchecked {\n"
"    image: url(:/qss_icons/rc/checkbox_unchecked.png);\n"
"}\n"
"\n"
"QTreeView::indicator:indeterminate,\n"
"QListView::indicator:indeterminate {\n"
"    image: url(:/qss_icons/rc/checkbox_indeterminate.png);\n"
"}\n"
"\n"
"QTreeView::indicator:checked:hover,\n"
"QTreeView::indicator:checked:focus,\n"
"QTreeView::indicator:checked:pressed,\n"
"QListView::indicator:checked:hover,\n"
"QListView::indicator:checked:focus,\n"
"QListView::indicator:checked:pressed {\n"
"    image: url(:/qss_icons/rc/checkbox_checked_focus.png);\n"
"}\n"
"\n"
"QTreeView::indicator:unchecked:hover,\n"
"QTreeView::indicator:unchecked:focus,\n"
"QTreeView::indicator:unchecked:pressed,\n"
"QListView::indicator:unchecked:hover,\n"
"QListView::indicator:unchecked:focus,\n"
"QListView::indicator:unchecked:pressed {\n"
"    image: url(:/qss_icons/rc/checkbox_unchecked_focus.png);\n"
"}\n"
"\n"
"QTreeView::indicator:indeterminate:hover,\n"
"QTreeView::indicator:indeterminate:focus,\n"
"QTreeView::indicator:indeterminate:pressed,\n"
"QListView::indicator:indeterminate:hover,\n"
"QListView::indicator:indeterminate:focus,\n"
"QListView::indicator:indeterminate:pressed {\n"
"    image: url(:/qss_icons/rc/checkbox_indeterminate_focus.png);\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #565a5e;\n"
"    height: 4px;\n"
"    background: #565a5e;\n"
"    margin: 0px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #232629;\n"
"    border: 1px solid #565a5e;\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    margin: -8px 0;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border: 1px solid #565a5e;\n"
"    width: 4px;\n"
"    background: #565a5e;\n"
"    margin: 0px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background: #232629;\n"
"    border: 1px solid #565a5e;\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    margin: 0 -8px;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: transparent;\n"
"    border: 1px transparent #76797C;\n"
"    border-radius: 2px;\n"
"    margin: 3px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"] {\n"
"    /* only for MenuButtonPopup */\n"
"    padding-right: 20px;\n"
"    /* make way for the popup button */\n"
"    border: 1px #76797C;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"2\"] {\n"
"    /* only for InstantPopup */\n"
"    padding-right: 10px;\n"
"    /* make way for the popup button */\n"
"    border: 1px #76797C;\n"
"}\n"
"\n"
"QToolButton:hover,\n"
"QToolButton::menu-button:hover {\n"
"    background-color: transparent;\n"
"    border: 1px solid #3daee9;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QToolButton:checked,\n"
"QToolButton:pressed,\n"
"QToolButton::menu-button:pressed {\n"
"    background-color: #3daee9;\n"
"    border: 1px solid #3daee9;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"\n"
"/* the subcontrol below is used only in the InstantPopup or DelayedPopup mode */\n"
"\n"
"QToolButton::menu-indicator {\n"
"    image: url(:/qss_icons/rc/down_arrow.png);\n"
"    top: -7px;\n"
"    left: -2px;\n"
"    /* shift it a bit */\n"
"}\n"
"\n"
"\n"
"/* the subcontrols below are used only in the MenuButtonPopup mode */\n"
"\n"
"QToolButton::menu-button {\n"
"    border: 1px transparent #76797C;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    /* 16px width + 4px for border = 20px allocated above */\n"
"    width: 16px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QToolButton::menu-arrow {\n"
"    image: url(:/qss_icons/rc/down_arrow.png);\n"
"}\n"
"\n"
"QToolButton::menu-arrow:open {\n"
"    border: 1px solid #76797C;\n"
"}\n"
"\n"
"\n"
"\n"
"QTableView {\n"
"    border: 1px solid #76797C;\n"
"    gridline-color: #31363b;\n"
"    background-color: #232629;\n"
"}\n"
"\n"
"QTableView,\n"
"QHeaderView {\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QTableView::item:pressed,\n"
"QListView::item:pressed,\n"
"QTreeView::item:pressed {\n"
"    background: #18465d;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QTableView::item:selected:active,\n"
"QTreeView::item:selected:active,\n"
"QListView::item:selected:active {\n"
"    background: #287399;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QHeaderView {\n"
"    background-color: #31363b;\n"
"    border: 1px transparent;\n"
"    border-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #31363b;\n"
"    color: #eff0f1;\n"
"    padding: 5px;\n"
"    border: 1px solid #76797C;\n"
"    border-radius: 0px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"QHeaderView::section::vertical::only-one {\n"
"    border-top: 1px solid #76797C;\n"
"}\n"
"\n"
"QHeaderView::section::vertical {\n"
"    border-top: transparent;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"QHeaderView::section::horizontal::only-one {\n"
"    border-left: 1px solid #76797C;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal {\n"
"    border-left: transparent;\n"
"}\n"
"\n"
"QHeaderView::section:checked {\n"
"    color: white;\n"
"    background-color: #334e5e;\n"
"}\n"
"\n"
"\n"
"/* style the sort indicator */\n"
"\n"
"QHeaderView::down-arrow {\n"
"    image: url(:/qss_icons/rc/down_arrow.png);\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    image: url(:/qss_icons/rc/up_arrow.png);\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #31363b;\n"
"    border: 1px transparent #76797C;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QToolBox {\n"
"    padding: 5px;\n"
"    border: 1px transparent black;\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"    color: #eff0f1;\n"
"    background-color: #31363b;\n"
"    border: 1px solid #76797C;\n"
"    border-bottom: 1px transparent #31363b;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"QToolBox::tab:selected {\n"
"    /* italicize selected tabs */\n"
"    font: italic;\n"
"    background-color: #31363b;\n"
"    border-color: #3daee9;\n"
"}\n"
"\n"
"QStatusBar::item {\n"
"    border: 0px transparent dark;\n"
"}\n"
"\n"
"QFrame[height=\"3\"],\n"
"QFrame[width=\"3\"] {\n"
"    background-color: #76797C;\n"
"}\n"
"\n"
"QSplitter::handle {\n"
"    border: 1px dashed #76797C;\n"
"}\n"
"\n"
"QSplitter::handle:hover {\n"
"    background-color: #787876;\n"
"    border: 1px solid #76797C;\n"
"}\n"
"\n"
"QSplitter::handle:horizontal {\n"
"    width: 1px;\n"
"}\n"
"\n"
"QSplitter::handle:vertical {\n"
"    height: 1px;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: 1px solid #76797C;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #05B8CC;\n"
"}\n"
"\n"
"QDateEdit {\n"
"    selection-background-color: #3daee9;\n"
"    border-style: solid;\n"
"    border: 1px solid #3375A3;\n"
"    border-radius: 2px;\n"
"    padding: 1px;\n"
"    min-width: 75px;\n"
"}\n"
"\n"
"QDateEdit:on {\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #4a4a4a;\n"
"}\n"
"\n"
"QDateEdit QAbstractItemView {\n"
"    background-color: #232629;\n"
"    border-radius: 2px;\n"
"    border: 1px solid #3375A3;\n"
"    selection-background-color: #3daee9;\n"
"}\n"
"\n"
"QDateEdit::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 0px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow {\n"
"    image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"}\n"
"\n"
"QDateEdit::down-arrow:on,\n"
"QDateEdit::down-arrow:hover,\n"
"QDateEdit::down-arrow:focus {\n"
"    image: url(:/qss_icons/rc/down_arrow.png);\n"
"}\n"
"\n"
"QTreeView {\n"
"        background-color: transparent;\n"
"        color: #546E7A;\n"
"        outline: 0;\n"
"        border: 0;\n"
"}\n"
"\n"
"QTreeView::item:hover {\n"
"        background-color: transparent;\n"
"        color: #AFBDC4;\n"
"}\n"
"\n"
"QTreeView::item:selected {\n"
"        background-color: transparent;\n"
"        color: #FFFFFF;\n"
"}\n"
"\n"
"QTreeView QHeaderView:section {\n"
"        background-color: #263238;\n"
"        color: #CFD8DC;\n"
"        border: 0;\n"
"}\n"
"\n"
"QTreeView::indicator:checked {\n"
"        background-color: qradialgradient(cx:0.5, cy:0.5, fx:0.25, fy:0.15, radius:0.3, stop:0 #80CBC4, stop:1 #263238);\n"
"        border: 1px solid #536D79;\n"
"        selection-background-color: transparent;\n"
"}\n"
"\n"
"QTreeView::indicator:unchecked {            /* This and the one above style the checkbox in the Options -> Keyboard */\n"
"        background-color: #263238;                /* This is still a hover over in blue I can\'t get rid of */\n"
"        border: 1px solid #536D79;\n"
"        selection-background-color: transparent;\n"
"}\n"
"\n"
"/*QTreeView QScrollBar {\n"
"        background-color: #263238\n"
"}*/\n"
"\n"
"QTreeView::branch {\n"
"        /* Skip - applies to everything */\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item {\n"
"        /* Skip - files */\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:!adjoins-item {\n"
"        /* Skip - applies to almost all on the left side */\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children:has-siblings {\n"
"        background: url(\'./images/rightarrowgray.png\') center center no-repeat;\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed {\n"
"        background: url(\'./images/rightarrowgray.png\') center center no-repeat;\n"
"}\n"
"\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item {\n"
"        /* Skip - files */\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:has-siblings {\n"
"        background: url(\'./images/downarrowgray.png\') center center no-repeat;\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings {\n"
"        background: url(\'./images/downarrowgray.png\') center center no-repeat;\n"
"}\n"
"\n"
"/* === QScrollBar:horizontal === */\n"
"QScrollBar:horizontal {\n"
"        background: #263238;                /* Background where slider is not */\n"
"        height: 10px;\n"
"        margin: 0;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"        background: #263238;                /* Background where slider is not */\n"
"        width: 10px;\n"
"        margin: 0;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #37474F;                    /* Slider color */\n"
"    min-width: 16px;\n"
"        border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #37474F;                    /* Slider color */\n"
"    min-height: 16px;\n"
"        border-radius: 5px;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal,\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"        background: none;                                                /* Removes the dotted background */\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal,\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {    /* Hides the slider arrows */\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"\n"
"QLineEdit {\n"


"        color: white;\n"
"}\n"
"\n"
"QSpinBox {\n"
"        background: transparent;\n"
"        border: 1px solid transparent;\n"
"        color: #546E7A;\n"
"}\n"
"\n"
"/*****************************************************************************\n"
"Main Screen\n"
"*****************************************************************************/\n"
"QTreeView {\n"
"        background-color: #263238;\n"
"}\n"
"\n"
"QMenu {\n"
"        background-color: #263238;        /* File Menu Background color */\n"
"        color: #546E7A;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"        color: #AFBDC4;\n"
"}\n"
"\n"
"QMenu::item:pressed {\n"
"        color: #FFFFFF;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"        height: 1px;\n"
"        background: transparent;            /* Could change this to #546E7A and reduce the margin top and bottom to 1px */\n"
"        margin-left: 10px;\n"
"        margin-right: 10px;\n"
"        margin-top: 5px;\n"
"        margin-bottom: 5px;\n"
"}\n"
"\n"
"/* === QMenuBar === */\n"
"QMenuBar {\n"
"        background-color: #263238;\n"
"        color: #546E7A;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"        background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:disabled {\n"
"        color: gray;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"        color: #AFBDC4;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"        color: #FFFFFF;\n"
"}\n"
"\n"
"QToolBar {\n"
"        background: #263238;\n"
"        border: 1px solid transparent;\n"
"}\n"
"\n"
"QToolBar:handle {\n"
"        background: transparent;\n"
"        border-left: 2px dotted #80CBC4;    /* Fix the 4 handle dots so it doesn\'t look crappy */\n"
"        color: transparent;\n"
"}\n"
"\n"
"QToolBar::separator {\n"
"        border: 0;\n"
"}\n"
"\n"
"/* === QToolButton === */\n"
"QToolButton:hover, QToolButton:pressed {\n"
"        background-color: transparent;\n"
"}\n"
"\n"
"QToolButton::menu-button {\n"
"        background: url(\'./images/downarrowgray.png\') center center no-repeat;\n"
"        background-color: #263238;                                                /* This needs to be set to ensure the other brown arrows don\'t show */\n"
"}\n"
"\n"
"QToolButton::menu-button:hover, QToolButton::menu-button:pressed {\n"
"        background-color: #263238;\n"
"}\n"
"\n"
"QStatusBar {\n"
"        background-color: #263238;\n"
"}\n"
"\n"
"QLabel {\n"
"        color: #546E7A;        /* Text at the bottom right corner of the screen */\n"
"}\n"
"\n"
"QToolButton {    /* I don\'t like how the items depress */\n"
"        color: #546E7A;\n"
"}\n"
"\n"
"QToolButton:hover, QToolButton:pressed, QToolButton:checked {\n"
"        background-color: #263238;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"        color: #AFBDC4;\n"
"\n"
"}\n"
"\n"
"QToolButton:checked, QToolButton:pressed {\n"
"        color: #FFFFFF;\n"
"}\n"
"\n"
"\n"
"QToolButton {\n"
"        border: 1px solid transparent;\n"
"        margin: 1px;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"        background-color: transparent;                /* I don\'t like how the down arrows in the top menu bar move down when clicked */\n"
"        border: 1px solid transparent;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"] { /* only for MenuButtonPopup */\n"
"        padding-right: 20px; /* make way for the popup button */\n"
"}\n"
"\n"
"QToolButton::menu-button {\n"
"        border-left: 1px solid transparent;\n"
"        background: transparent;\n"
"    width: 16px;\n"
"}\n"
"\n"
"QToolButton::menu-button:hover {\n"
"        border-left: 1px solid transparent;\n"
"        background: transparent;\n"
"    width: 16px;\n"
"}\n"
"\n"
"QStatusBar::item {\n"
"        color: #546E7A;\n"
"        background-color: #263238;\n"
"}\n"
"\n"
"QAbstractScrollArea  {    /* Borders around the code editor and debug window */\n"
"        border: 0;\n"
"}\n"
"\n"
"/*****************************************************************************\n"
"Play around with these settings\n"
"*****************************************************************************/\n"
"\n"
"/* Force the dialog\'s buttons to follow the Windows guidelines. */\n"
"QDialogButtonBox {\n"
"    button-layout: 0;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"        left: 0px; /* Test this out on OS X, it will affect the tabs in the Options Dialog, on OS X they are centered */\n"
"}\n"
"\n"
"\n"
"/**Added by Ansif**/\n"
"\n"
"QHeaderView::section {\n"
"    gridline-color: #fffff8;\n"
"color: #FFFFFF;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"   gridline-color: #fffff8;\n"
"color: #FFFFFF;\n"
"}\n"
"\n"
"QHeaderView::section:vertical\n"
"{\n"
"    gridline-color: #fffff8;\n"
"color: #FFFFFF;\n"


"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(12, 437, 781, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_7 = QtWidgets.QLabel(parent=self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 161, 21))
        self.label_7.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_7.setObjectName("label_7")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(parent=self.tab)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(0, 110, 194, 38))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.label_8 = QtWidgets.QLabel(parent=self.tab)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 161, 21))
        self.label_8.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.tab)
        self.dateTimeEdit.setGeometry(QtCore.QRect(0, 30, 194, 38))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(630, 30, 142, 38))
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"\n"
"\n"
"        color: white;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_9 = QtWidgets.QLabel(parent=self.tab)
        self.label_9.setGeometry(QtCore.QRect(650, 0, 55, 16))
        self.label_9.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_9.setObjectName("label_9")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(240, 40, 187, 220))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.checkBox = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkBox_6)
        self.checkBox_8 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_8.setObjectName("checkBox_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_9.setObjectName("checkBox_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_10.setObjectName("checkBox_10")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkBox_10)
        self.checkBox_7 = QtWidgets.QCheckBox(parent=self.formLayoutWidget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.checkBox_7)
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setGeometry(QtCore.QRect(250, 10, 171, 20))
        self.label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(460, 40, 142, 38))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_10 = QtWidgets.QLabel(parent=self.tab)
        self.label_10.setGeometry(QtCore.QRect(460, 20, 151, 20))
        self.label_10.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_15 = QtWidgets.QLabel(parent=self.tab)
        self.label_15.setGeometry(QtCore.QRect(460, 80, 151, 20))
        self.label_15.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_15.setObjectName("label_15")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(460, 100, 142, 38))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.comboBox = QtWidgets.QComboBox(parent=self.tab)
        self.comboBox.setGeometry(QtCore.QRect(460, 150, 150, 38))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(parent=self.tab)
        self.label_3.setGeometry(QtCore.QRect(460, 130, 151, 20))
        self.label_3.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton.setGeometry(QtCore.QRect(620, 140, 126, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.tab)
        self.pushButton_9.setGeometry(QtCore.QRect(470, 210, 126, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.listView = QtWidgets.QListView(parent=self.tab_2)
        self.listView.setGeometry(QtCore.QRect(0, 0, 791, 231))
        self.listView.setObjectName("listView")
        self.tabWidget.addTab(self.tab_2, "")
       
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.tab_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(562, 70, 211, 38))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.tab_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(542, 170, 211, 38))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_11 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(620, 40, 101, 20))
        self.label_11.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(620, 130, 101, 20))
        self.label_12.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_12.setObjectName("label_12")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.tab_3)
        self.buttonBox.setGeometry(QtCore.QRect(570, 170, 193, 28))
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox_2 = QtWidgets.QDialogButtonBox(parent=self.tab_3)
        self.buttonBox_2.setGeometry(QtCore.QRect(560, 220, 193, 41))
        self.buttonBox_2.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Discard)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.label_13 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(564, 0, 191, 20))
        self.label_13.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_13.setObjectName("label_13")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(160, 230, 126, 38))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_14 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(150, 1, 181, 20))
        self.label_14.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_14.setObjectName("label_14")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.tab_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(5, 30, 461, 191))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.tab_5)
        self.pushButton_8.setGeometry(QtCore.QRect(600, 30, 126, 38))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_16 = QtWidgets.QLabel(parent=self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(240, 0, 161, 20))
        self.label_16.setObjectName("label_16")
        self.tableWidget_3 = QtWidgets.QTableWidget(parent=self.tab_5)
        self.tableWidget_3.setGeometry(QtCore.QRect(20, 0, 561, 341))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.listView_2 = QtWidgets.QListView(parent=self.tab_6)
        self.listView_2.setGeometry(QtCore.QRect(0, 0, 791, 231))
        self.tabWidget.addTab(self.tab_6, "Packet Decode")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.listView_3 = QtWidgets.QListView(parent=self.tab_7)
        self.listView_3.setGeometry(QtCore.QRect(0, 0, 791, 231))
        self.tabWidget.addTab(self.tab_7, "Packet statictics")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.listView_4 = QtWidgets.QListView(parent=self.tab_8)
        self.listView_4.setGeometry(QtCore.QRect(0, 0, 391, 231))
        self.listView_4.setObjectName("listView_4")
        self.label_17 = QtWidgets.QLabel(parent=self.tab_8)
        self.label_17.setGeometry(QtCore.QRect(500, 110, 161, 20))
        self.label_17.setObjectName("label_17")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.tab_8)
        self.lineEdit_6.setGeometry(QtCore.QRect(500, 139, 171, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.tab_8)
        self.pushButton_10.setGeometry(QtCore.QRect(500, 180, 84, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.tab_8)
        self.pushButton_11.setGeometry(QtCore.QRect(590, 180, 84, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.tabWidget.addTab(self.tab_8, "Blacklist")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.listView_5 = QtWidgets.QListView(parent=self.tab_9)
        self.listView_5.setGeometry(QtCore.QRect(0, 0, 391, 231))
        self.listView_5.setObjectName("listView_5")
        self.label_18 = QtWidgets.QLabel(parent=self.tab_9)
        self.label_18.setGeometry(QtCore.QRect(500, 100, 261, 120))
        self.label_18.setObjectName("label_18")
        self.tab_fabricate_packet = QtWidgets.QWidget()



        # Increase size and set color to white
        self.label_18.setStyleSheet("color: white; font-size: 16px;")  # Set text color to white and font size
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.tab_9)
        self.pushButton_12.setGeometry(QtCore.QRect(500, 180, 84, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.tabWidget.addTab(self.tab_9, "Logging")
        self.tab_fabricate_packet.setObjectName("tab_fabricate_packet")

        # IP Source Label
                # IP Source Label
        self.label_ip_source = QtWidgets.QLabel(parent=self.tab_fabricate_packet)
        self.label_ip_source.setGeometry(QtCore.QRect(10, 20, 100, 20))
        self.label_ip_source.setObjectName("label_ip_source")
        self.label_ip_source.setStyleSheet("color: white; font-size: 12px;")  # Set text color to white and font size

        # IP Source LineEdit
        self.lineEdit_ip_source = QtWidgets.QLineEdit(parent=self.tab_fabricate_packet)
        self.lineEdit_ip_source.setGeometry(QtCore.QRect(10, 40, 200, 30))
        self.lineEdit_ip_source.setObjectName("lineEdit_ip_source")
        self.lineEdit_ip_source.setStyleSheet("""
        background-color: gray;
        color: white;
        """)

        # IP Dst Label
        self.label_ip_dst = QtWidgets.QLabel(parent=self.tab_fabricate_packet)
        self.label_ip_dst.setGeometry(QtCore.QRect(10, 80, 100, 20))
        self.label_ip_dst.setObjectName("label_ip_dst")
        self.label_ip_dst.setStyleSheet("color: white; font-size: 12px;")

        # IP Dst LineEdit
        self.lineEdit_ip_dst = QtWidgets.QLineEdit(parent=self.tab_fabricate_packet)
        self.lineEdit_ip_dst.setGeometry(QtCore.QRect(10, 110, 200, 30))
        self.lineEdit_ip_dst.setObjectName("lineEdit_ip_dst")
        self.lineEdit_ip_dst.setStyleSheet("""
        background-color: gray;
        color: white;
        """)

        # Pick a Protocol Label
        self.label_protocol = QtWidgets.QLabel(parent=self.tab_fabricate_packet)
        self.label_protocol.setGeometry(QtCore.QRect(240, 10, 120, 20))
        self.label_protocol.setObjectName("label_protocol")
        self.label_protocol.setStyleSheet("color: white; font-size: 12px;")

        # Protocol ComboBox
        self.comboBox_protocol = QtWidgets.QComboBox(parent=self.tab_fabricate_packet)
        self.comboBox_protocol.setGeometry(QtCore.QRect(240, 40, 150, 30))
        self.comboBox_protocol.setObjectName("comboBox_protocol")
        self.comboBox_protocol.addItems(["TCP", "UDP", "ICMP", "FTP", "HTTP", "HTTPS", "DNS", "DHCP"])
        self.comboBox_protocol.setStyleSheet("""
        background-color: gray;
        color: black;
        """)

        # Apply Button
        self.pushButton_apply = QtWidgets.QPushButton(parent=self.tab_fabricate_packet)
        self.pushButton_apply.setGeometry(QtCore.QRect(10, 160, 100, 30))  # Position below the other widgets
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.pushButton_apply.setText("Apply")
        

        # Add the tab to the TabWidget
        self.tabWidget.addTab(self.tab_fabricate_packet, "Fabricate packet")


        #
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(266, 10, 1031, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout.addWidget(self.pushButton_13)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 0, 71, 61))
        self.graphicsView.setObjectName("graphicsView")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(81, 3, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(864, 433, 311, 20))
        self.label_4.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1270, 70, 91, 20))
        self.label_5.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1290, 110, 55, 16))
        self.label_6.setObjectName("label_6")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1270, 180, 126, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1270, 250, 126, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 60, 1231, 361))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget_4 = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_4.setGeometry(QtCore.QRect(805, 460, 381, 271))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.graphicsView_2 = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(1210, 400, 300, 401))
        self.graphicsView_2.setObjectName("graphicsView_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1360, 26))
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(parent=self.menubar)
        self.menuHome.setObjectName("menuHome")
        self.menuTools = QtWidgets.QMenu(parent=self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuReports = QtWidgets.QMenu(parent=self.menubar)
        self.menuReports.setObjectName("menuReports")
        self.menuSettings = QtWidgets.QMenu(parent=self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.actionImport_Packets = QtGui.QAction(parent=MainWindow)
        self.actionImport_Packets.setObjectName("actionImport_Packets")
        self.actionExport_Packets = QtGui.QAction(parent=MainWindow)
        self.actionExport_Packets.setObjectName("actionExport_Packets")
        self.actionLive_Capture = QtGui.QAction(parent=MainWindow)
        self.actionLive_Capture.setObjectName("actionLive_Capture")
        self.menuHome.addAction(self.actionImport_Packets)
        self.menuHome.addAction(self.actionExport_Packets)
        self.menuHome.addAction(self.actionLive_Capture)
        self.menuTools.addSeparator()
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Start Time"))
        self.label_8.setText(_translate("MainWindow", "End Time"))
        self.label_9.setText(_translate("MainWindow", "Port"))
        self.checkBox.setText(_translate("MainWindow", "UDP"))
        self.checkBox_2.setText(_translate("MainWindow", "TCP"))
        self.checkBox_3.setText(_translate("MainWindow", "ICMP"))
        self.checkBox_4.setText(_translate("MainWindow", "DNS"))
        self.checkBox_5.setText(_translate("MainWindow", "HTTP"))
        self.checkBox_6.setText(_translate("MainWindow", "HTTPS"))
        self.checkBox_8.setText(_translate("MainWindow", "FTP"))
        self.checkBox_9.setText(_translate("MainWindow", "DHCP"))
        self.checkBox_10.setText(_translate("MainWindow", "Other"))
        self.checkBox_7.setText(_translate("MainWindow", "TELNET"))
        self.label.setText(_translate("MainWindow", "  Filter by Protocol"))
        self.label_10.setText(_translate("MainWindow", "Filter by source IP"))
        self.label_15.setText(_translate("MainWindow", "Filter by Destination IP"))
        self.comboBox.setItemText(0, _translate("MainWindow", "All"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Inside Traffic"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Outside Traffic"))
        self.label_3.setText(_translate("MainWindow", "Type Of Traffic"))
        self.pushButton.setText(_translate("MainWindow", "Reset"))
        self.pushButton_9.setText(_translate("MainWindow", "Apply"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Packet Filter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Packet Details"))
        self.label_11.setText(_translate("MainWindow", "Device name"))
        self.label_12.setText(_translate("MainWindow", "MAC Address"))
        self.label_13.setText(_translate("MainWindow", "              Add/Remove Sensor"))
        self.pushButton_7.setText(_translate("MainWindow", "Focus on"))
        self.label_14.setText(_translate("MainWindow", "                All Devices"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", " Sensors "))
        self.pushButton_8.setText(_translate("MainWindow", "Focus on"))
        self.pushButton_10.setText(_translate("MainWindow", "Add"))
        self.pushButton_11.setText(_translate("MainWindow", "Remove"))
        self.pushButton_12.setText(_translate("MainWindow", "Save"))
        self.label_16.setText(_translate("MainWindow", "Running Applications"))
        self.label_17.setText(_translate("MainWindow", "Enter IP Address"))
        self.label_18.setText(_translate("MainWindow", "Save Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Application Filter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Packet Decode"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Packet Statistics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Blacklist"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Logging"))
        self.pushButton_4.setText(_translate("MainWindow", "Home"))
        self.pushButton_13.setText(_translate("MainWindow", "Incident Response"))
        self.pushButton_3.setText(_translate("MainWindow", "Tools"))
        self.pushButton_2.setText(_translate("MainWindow", "Analysis"))
        self.label_2.setText(_translate("MainWindow", "Naswail"))
        self.label_4.setText(_translate("MainWindow", "                      Suspicious Packets"))
        self.label_5.setText(_translate("MainWindow", "Time Elapsed:"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_ip_dst.setText(_translate("MainWindow", "Enter destination IP"))
        self.label_ip_source.setText(_translate("MainWindow", "Enter source IP"))
        self.label_protocol.setText(_translate("MainWindow", "Enter protocol"))
        self.pushButton_5.setText(_translate("MainWindow", "Start Capture"))
        self.pushButton_6.setText(_translate("MainWindow", "Stop Capture"))
        self.menuHome.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuReports.setTitle(_translate("MainWindow", "Reports"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionImport_Packets.setText(_translate("MainWindow", "Import Packets"))
        self.actionExport_Packets.setText(_translate("MainWindow", "Export Packets"))
        self.actionLive_Capture.setText(_translate("MainWindow", "Live Capture"))
