# Form implementation generated from reading ui file 'toolup.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Naswail_Tool(object):
    def setupUi(self, Naswail_Tool):
        Naswail_Tool.setObjectName("Naswail_Tool")
        Naswail_Tool.resize(1600, 900)
        Naswail_Tool.setMinimumSize(QtCore.QSize(1200, 800))
        Naswail_Tool.setStyleSheet("/* Main Application Background */\n"
"QWidget {\n"
"    background-color: #2D2A2E;\n"
"    color: #40E0D0; /* Turquoise text */\n"
"    font-family: \"Consolas\", \"Monospace\";\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Table View Text */\n"
"QTableView {\n"
"    color: #FFFFFF; /* White text for table content */\n"
"}\n"
"\n"
"/* Buttons */\n"
"QPushButton {\n"
"    background-color: #40E0D0; /* Turquoise */\n"
"    color: #2D2A2E;\n"
"    border: 1px solid #40E0D0;\n"
"    border-radius: 4px;\n"
"    padding: 5px 10px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #36C9B0;\n"
"    border: 1px solid #36C9B0;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2DB39E;\n"
"    border: 1px solid #2DB39E;\n"
"}\n"
"\n"
"/* Text Inputs */\n"
"QLineEdit, QTextEdit {\n"
"    background-color: #3E3D40;\n"
"    color: #40E0D0; /* Turquoise text */\n"
"    border: 1px solid #5A595C;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLineEdit:focus, QTextEdit:focus {\n"
"    border: 1px solid #40E0D0;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #40E0D0;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Scrollbars */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background-color: rgba(90, 89, 92, 150);\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* Graphics View */\n"
"QGraphicsView {\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"/* Menus */\n"
"QMenuBar {\n"
"    background-color: #2D2A2E;\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #5A595C;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #3E3D40;\n"
"    color: #40E0D0;\n"
"    border: 1px solid #5A595C;\n"
"}\n"
"\n"
"/* Tabs */\n"
"QTabBar::tab {\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Sliders */\n"
"QSlider::handle:horizontal {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Progress Bars */\n"
"QProgressBar {\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Checkboxes/Radio */\n"
"QCheckBox, QRadioButton {\n"
"    color: #40E0D0;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked, QRadioButton::indicator:checked {\n"
"    background-color: #40E0D0;\n"
"}\n"
"\n"
"/* Group Boxes */\n"
"QGroupBox {\n"
"    color: #40E0D0;\n"
"    border: 1px solid #40E0D0;\n"
"    border-radius: 4px;\n"
"    margin-top: 10px;\n"
"    padding-top: 15px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 5px;\n"
"}\n"
"\n"
"/* ComboBox */\n"
"QComboBox {\n"
"    background-color: #3E3D40;\n"
"    color: #40E0D0;\n"
"    border: 1px solid #5A595C;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/down_arrow.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #3E3D40;\n"
"    color: #40E0D0;\n"
"    selection-background-color: #5A595C;\n"
"}\n"
"")

        # Navigation Bar - EXACTLY as in UI_Main.py but adapted for QWidget
        self.graphicsView = QtWidgets.QGraphicsView(parent=Naswail_Tool)
        self.graphicsView.setGeometry(QtCore.QRect(10, 0, 71, 61))
        self.graphicsView.setObjectName("graphicsView")
        
        self.label_4 = QtWidgets.QLabel(parent=Naswail_Tool)
        self.label_4.setGeometry(QtCore.QRect(81, 3, 220, 53))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Small Semibol")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(85)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Naswail_Tool)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(266, 10, 1031, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.pushButton_8)
        
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        
        self.horizontalLayout.addSpacing(10)
        
        # Notification Button (exactly like in UI_Main)
        self.notificationButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.notificationButton.setText("🔔")
        self.notificationButton.setFixedSize(40, 30)
        self.notificationButton.setObjectName("notificationButton")
        self.notificationButton.setStyleSheet("""
                QPushButton {
                background-color: #40E0D0;
                color: #2D2A2E;
                border: 1px solid #40E0D0;
                border-radius: 15px;
                font-size: 16px;
                }
                QPushButton:hover {
                background-color: #36C9B0;
                border: 1px solid #36C9B0;
                }
                QPushButton:pressed {
                background-color: #2DB39E;
                border: 1px solid #2DB39E;
                }
        """)
        self.horizontalLayout.addWidget(self.notificationButton)
        
        # Notification Menu - matching UI_Main
        self.notificationMenu = QtWidgets.QMenu(parent=Naswail_Tool)
        self.notificationMenu.setStyleSheet("""
                QMenu {
                background-color: #3E3D40;
                color: #FFFFFF;
                border: 1px solid #5A595C;
                border-radius: 5px;
                padding: 5px;
                }
        """)
        
        self.notificationList = QtWidgets.QListWidget()
        self.notificationList.setFixedSize(300, 200)
        self.notificationList.setStyleSheet("""
                QListWidget {
                background-color: #3E3D40;
                border: none;
                font-size: 14px;
                }
        """)
        
        notificationWidgetAction = QtWidgets.QWidgetAction(self.notificationMenu)
        notificationWidgetAction.setDefaultWidget(self.notificationList)
        self.notificationMenu.addAction(notificationWidgetAction)

        # Scroll Area for Content
        self.scrollArea = QtWidgets.QScrollArea(parent=Naswail_Tool)
        self.scrollArea.setGeometry(QtCore.QRect(20, 70, 1560, 800))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(1400, 2500))
        
        # Main content layout
        self.contentLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.contentLayout.setContentsMargins(40, 25, 40, 60)
        self.contentLayout.setSpacing(50)

        # SECTION 1: Traffic Prediction
        self.predictionGroupBox = QtWidgets.QGroupBox("Traffic Prediction")
        predictionLayout = QtWidgets.QVBoxLayout(self.predictionGroupBox)
        predictionLayout.setContentsMargins(30, 25, 30, 25)
        predictionLayout.setSpacing(20)

        # Prediction table and graph
        self.predictionDisplayLayout = QtWidgets.QHBoxLayout()
        
        # Left side: Table with input controls underneath
        self.leftPredictionLayout = QtWidgets.QVBoxLayout()
        
        # Time table with increased width
        self.tableWidget_3 = QtWidgets.QTableWidget()
        self.tableWidget_3.setMinimumWidth(450)  # Further increased width to avoid truncation
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(7)
        self.tableWidget_3.setHorizontalHeaderLabels(["Time", "Packet Estimate"])
        self.tableWidget_3.setVerticalHeaderLabels(["Current", "Desired Time", "+ 1 Hour", "+ 3 Hour", "+ 6 Hour", "+ 12 Hour", "+ 24 Hour"])
        
        # Add table to layout
        self.leftPredictionLayout.addWidget(self.tableWidget_3)
        self.leftPredictionLayout.addSpacing(15)
        
        # Add input controls under the table
        self.inputControlsLayout = QtWidgets.QHBoxLayout()
        self.label_5 = QtWidgets.QLabel("Enter Number of Hours:")
        self.lineEdit = QtWidgets.QLineEdit()
        self.lineEdit.setMaximumWidth(100)
        self.pushButton = QtWidgets.QPushButton("Predict")
        self.pushButton.setMinimumWidth(120)
        
        self.inputControlsLayout.addWidget(self.label_5)
        self.inputControlsLayout.addWidget(self.lineEdit)
        self.inputControlsLayout.addWidget(self.pushButton)
        self.inputControlsLayout.addStretch()
        
        self.leftPredictionLayout.addLayout(self.inputControlsLayout)
        
        # Add left side layout to main prediction layout
        self.predictionDisplayLayout.addLayout(self.leftPredictionLayout)
        
        # Right side: Graph
        self.widget = QtWidgets.QWidget()
        self.widget.setMinimumSize(QtCore.QSize(800, 450))
        
        # Add graph to layout with stretch priority
        self.predictionDisplayLayout.addWidget(self.widget, 1)
        
        predictionLayout.addLayout(self.predictionDisplayLayout)
        self.contentLayout.addWidget(self.predictionGroupBox)

        # SECTION 2: Network Activity Monitoring
        self.networkActivityGroupBox = QtWidgets.QGroupBox("Network Activity Monitoring")
        networkActivityLayout = QtWidgets.QVBoxLayout(self.networkActivityGroupBox)
        networkActivityLayout.setContentsMargins(30, 25, 30, 25)
        networkActivityLayout.setSpacing(20)

        # Network activity list
        self.listView_2 = QtWidgets.QListView()
        self.listView_2.setMinimumHeight(450)
        networkActivityLayout.addWidget(self.listView_2)

        # Network activity controls - moved to bottom and centered
        self.networkControlsLayout = QtWidgets.QHBoxLayout()
        self.pushButton_5 = QtWidgets.QPushButton("Save")
        self.pushButton_5.setMinimumWidth(200)
        self.pushButton_7 = QtWidgets.QPushButton("Refresh")
        self.pushButton_7.setMinimumWidth(200)
        self.networkControlsLayout.addStretch()
        self.networkControlsLayout.addWidget(self.pushButton_5)
        self.networkControlsLayout.addSpacing(30)
        self.networkControlsLayout.addWidget(self.pushButton_7)
        self.networkControlsLayout.addStretch()
        networkActivityLayout.addLayout(self.networkControlsLayout)

        self.contentLayout.addWidget(self.networkActivityGroupBox)

        # SECTION 3: Corrupted Packets
        self.corruptedPacketsGroupBox = QtWidgets.QGroupBox("Corrupted Packets")
        corruptedPacketsLayout = QtWidgets.QVBoxLayout(self.corruptedPacketsGroupBox)
        corruptedPacketsLayout.setContentsMargins(30, 25, 30, 25)
        corruptedPacketsLayout.setSpacing(20)

        # Corrupted packets table - moved to top
        self.tableWidget_6 = QtWidgets.QTableWidget()
        self.tableWidget_6.setMinimumHeight(350)
        self.tableWidget_6.setColumnCount(11)
        self.tableWidget_6.setHorizontalHeaderLabels(
            ["Timestamp", "Source", "Destination", "Protocol", "Layer", "MAC Src", "MAC Dst", "Src Port", "Dst Port", "Length", "IP Version"]
        )
        corruptedPacketsLayout.addWidget(self.tableWidget_6)

        # Filter controls - moved to bottom
        self.filterControlsLayout = QtWidgets.QHBoxLayout()
        self.pushButton_11 = QtWidgets.QPushButton("Apply Filter")
        self.pushButton_11.setMinimumWidth(180)
        self.pushButton_6 = QtWidgets.QPushButton("Reset Filter")
        self.pushButton_6.setMinimumWidth(180)
        self.filterControlsLayout.addStretch()
        self.filterControlsLayout.addWidget(self.pushButton_11)
        self.filterControlsLayout.addSpacing(30)
        self.filterControlsLayout.addWidget(self.pushButton_6)
        self.filterControlsLayout.addStretch()
        corruptedPacketsLayout.addLayout(self.filterControlsLayout)

        # Filter options - moved under the table
        self.filterOptionsGroup = QtWidgets.QGroupBox("Filter Options")
        self.filterOptionsGroup.setMaximumHeight(240)
        self.filterOptionsLayout = QtWidgets.QHBoxLayout(self.filterOptionsGroup)
        self.filterOptionsLayout.setContentsMargins(20, 20, 20, 20)
        self.filterOptionsLayout.setSpacing(40)
        
        # Protocol filters - Updated to match UI_Main.py
        self.protocolFiltersGroup = QtWidgets.QGroupBox("Protocol Filters")
        protocolFiltersLayout = QtWidgets.QFormLayout(self.protocolFiltersGroup)
        protocolFiltersLayout.setContentsMargins(15, 20, 15, 15)
        protocolFiltersLayout.setVerticalSpacing(12)
        protocolFiltersLayout.setHorizontalSpacing(20)
        
        # Create checkboxes in the same layout as UI_Main.py
        self.checkBox_21 = QtWidgets.QCheckBox("UDP")
        self.checkBox_22 = QtWidgets.QCheckBox("TCP")
        self.checkBox_23 = QtWidgets.QCheckBox("ICMP")
        self.checkBox_24 = QtWidgets.QCheckBox("DNS")
        self.checkBox_25 = QtWidgets.QCheckBox("HTTP")
        self.checkBox_26 = QtWidgets.QCheckBox("HTTPS")
        self.checkBox_30 = QtWidgets.QCheckBox("TELNET")
        self.checkBox_27 = QtWidgets.QCheckBox("FTP")
        self.checkBox_28 = QtWidgets.QCheckBox("DHCP")
        self.checkBox_29 = QtWidgets.QCheckBox("Other")

        # Add to layout in matching pattern
        protocolFiltersLayout.addRow(self.checkBox_21, self.checkBox_25)
        protocolFiltersLayout.addRow(self.checkBox_22, self.checkBox_26)
        protocolFiltersLayout.addRow(self.checkBox_23, self.checkBox_30)
        protocolFiltersLayout.addRow(self.checkBox_24, self.checkBox_27)
        protocolFiltersLayout.addRow(self.checkBox_28, self.checkBox_29)
        
        self.filterOptionsLayout.addWidget(self.protocolFiltersGroup)

        # IP filters
        self.ipFiltersGroup = QtWidgets.QGroupBox("IP Filters")
        ipFiltersLayout = QtWidgets.QFormLayout(self.ipFiltersGroup)
        ipFiltersLayout.setContentsMargins(20, 20, 20, 20)
        ipFiltersLayout.setVerticalSpacing(15)
        ipFiltersLayout.setHorizontalSpacing(20)
        self.lineEdit_8 = QtWidgets.QLineEdit()
        self.lineEdit_9 = QtWidgets.QLineEdit()
        self.comboBox_3 = QtWidgets.QComboBox()
        self.comboBox_3.addItems(["All", "Inside Traffic", "Outside Traffic"])
        
        ipFiltersLayout.addRow("Source IP:", self.lineEdit_8)
        ipFiltersLayout.addRow("Destination IP:", self.lineEdit_9)
        ipFiltersLayout.addRow("Traffic Type:", self.comboBox_3)
        
        self.filterOptionsLayout.addWidget(self.ipFiltersGroup)
        
        corruptedPacketsLayout.addWidget(self.filterOptionsGroup)

        self.contentLayout.addWidget(self.corruptedPacketsGroupBox)

        # Add some space at the bottom
        self.contentLayout.addSpacing(40)

        # Set the scroll area widget
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Naswail_Tool)
        QtCore.QMetaObject.connectSlotsByName(Naswail_Tool)

    def retranslateUi(self, Naswail_Tool):
        _translate = QtCore.QCoreApplication.translate
        Naswail_Tool.setWindowTitle(_translate("Naswail_Tool", "Naswail - Tools"))
        self.label_4.setText(_translate("Naswail_Tool", "Naswail"))
        self.pushButton_4.setText(_translate("Naswail_Tool", "Home"))
        self.pushButton_8.setText(_translate("Naswail_Tool", "Incident Response"))
        self.pushButton_3.setText(_translate("Naswail_Tool", "Tools"))
        self.pushButton_2.setText(_translate("Naswail_Tool", "Analysis"))
        self.label_5.setText(_translate("Naswail_Tool", "Enter Number of Hours:"))
        self.pushButton.setText(_translate("Naswail_Tool", "Predict"))
        self.pushButton_5.setText(_translate("Naswail_Tool", "Save"))
        self.pushButton_7.setText(_translate("Naswail_Tool", "Refresh"))
        self.pushButton_6.setText(_translate("Naswail_Tool", "Reset Filter"))
        self.pushButton_11.setText(_translate("Naswail_Tool", "Apply Filter"))
        self.filterOptionsGroup.setTitle(_translate("Naswail_Tool", "Filter Options"))
        self.protocolFiltersGroup.setTitle(_translate("Naswail_Tool", "Protocol Filters"))
        self.ipFiltersGroup.setTitle(_translate("Naswail_Tool", "IP Filters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Naswail_Tool = QtWidgets.QWidget()
    ui = Ui_Naswail_Tool()
    ui.setupUi(Naswail_Tool)
    Naswail_Tool.show()
    sys.exit(app.exec())
